### ISSUE TITLE
Minority party committee URLs?

### ISSUE THREAD

**Issue by nickom** [unitedstates/congress-legislators#108]
I noticed that there are URLs listed for committees and sometimes the "minority_rss_url" but there isn't the minority URL. Is there a reason for that? Should there be a "minority_url" field?

For example:

House Committee on Small Business has this listed as the URL:
http://smallbusiness.house.gov/

But there is also the minority's site here that I can't find listed on /unitedstates:
http://democrats.smallbusiness.house.gov/

**Comment by konklone** [comment]
Still sounds like a good idea! :+1:

**Comment by timball** [comment]
still a thing either my PR or @nickom  I dont care-ish as long as its there

**Comment by mattpaz** [comment]
I think this is more or less occuring now.  There are several committees with `minority_url` populated. This could probably be closed.

**Comment by JoshData** [comment]
Yeah I'll close. Happy to reopen if there's interest & need.
