### ISSUE TITLE
Should we fill in gender for historical legislators?

### ISSUE THREAD

**Issue by wilson428** [unitedstates/congress-legislators#144]
House.gov lists all [297 women ever in Congress](http://history.house.gov/Exhibition-and-Publications/WIC/Women-in-Congress/). The other 11,000-some were presumably men.  

```legislators-historical.yaml``` is updated by hand, right?

**Comment by dannguyen** [comment]
Any resolution on this? At the very least, I could write something to fill in "M" for [everyone before 1916](http://en.wikipedia.org/wiki/Jeannette_Rankin)...that would require no scraping.

**Comment by JoshData** [comment]
The fastest thing is probably to manually link up the remaining 70-ish women listed on the House History website, then run my `house_history_gender.py` script, and then mark anyone who doesn't yet have a gender to `M`.

**Comment by dannguyen** [comment]
This quickie script -- based on finding all null-gendered legislators, starting post-1916, and with traditional female names, yields 142 possibilities...guess it'll be more hand-input than I thought it'd be :)

```ruby
require 'yaml'
require 'gender_detector'
require 'andand'


peeps = YAML.load_file('./legislators-historical.yaml').select do |p|
  # first term starts 1916 or after
  # http://en.wikipedia.org/wiki/Jeannette_Rankin
  p['terms'].andand[0]['start'] >= '1916' &&
  # Just the nulls
  p['bio'].andand['gender'].nil?
end

women = peeps.select{|p| d.get_gender(p['name']['first']) == :female}
# 142 candidates
```

**Comment by wilson428** [comment]
awesome!

**Comment by JoshData** [comment]
I suddenly had a need for this too, so I'll be landing a commit shortly filling in the remaining `gender` fields.
