### ISSUE TITLE
Determine how to handle mid-term changes to term-specific information

### ISSUE THREAD

**Issue by GPHemsley** [unitedstates/congress-legislators#17]
As mentioned in #10 and #15, certain change can occur within a traditional term of office that affect data that we would normally associate with a given term, the most prominent of which being the party affiliation and caucus preference of a member.

My proposal of abusing/redefining "term" to have a separate one for each change met with controversy, so other ideas are necessary.

**Comment by JoshData** [comment]
Fixed long ago in #198.
