### ISSUE TITLE
114th Congress Update Strategy

### ISSUE THREAD

**Issue by JoshData** [unitedstates/congress-legislators#223]
Hey,

Let's use this issue to plan how to update for the 114th Congress.

Something like:
- [x] Identify current Members that won, copy their term info forward but update dates. Check if anyone changed district/party (not likely). Be careful if any representatives became senators. - @joshdata
- [x] Move incumbents that lost to the historical file. (nb. Not everyone was up for reelection.) - @joshdata
- [x] Identify if any new members served in Congress previously and bring their records forward w/ a new term. - @joshdata
- [x] Add remaining new members.
- [x] Review junior/senior status
- [x] Add end dates to all current `leadership_roles` (no leadership_role should extend into the next Congress) - @rshorey or @handlers 
- [x] Add `leadership_roles` for the 114th Congress (#235)
- [ ] Not sure what to do about committees. There won't be committee assignments initially.
- [ ] [Photos](https://github.com/unitedstates/images)? Did/will GPO publish a new member directory?
- [X] Fill in bioguide IDs when they become available.
- [X] Delete retirees' `social-media` records.
- [ ] Add new members' social media accounts. (#234)
- [ ] After the 114th Congress begins, fill in missing data.

I'd like to set up a google doc spreadsheet where the rows are all of the offices that were up for election (all representatives, presumably all delegates, not sure about Puerto Rico, and one of the Senate classes) so we can make sure we take care of each election result.

@dwillis Any overlap with open elections data?

Did I miss anything?

cc @handlers @konklone

**Comment by JoshData** [comment]
All of the core stuff is ready to go in #230. I want to get this merged asap, so last call.... Thanks for everyone's help getting this far.

**Comment by handlers** [comment]
Oh wow — thanks! :+1:  from me on the merge of #230 .

**Comment by rshorey** [comment]
Sounds good to me. Do we have the promised xml file with bioguide IDs yet?

**Comment by JoshData** [comment]
A little birdie told me to guess the IDs by looking at the next sequential IDs --- I actually committed a script that reports the next set of bioguide IDs. (It doesn't work perfectly.) So I did that and entered all of the bioguide IDs for the new members. (I also copied in the new opensecrets IDs.)

We should be on the lookout for when LIS IDs are posted at http://www.senate.gov/general/contact_information/senators_cfm.xml.

**Comment by rshorey** [comment]
I'm using that same CSV to deal with contact congress so having them already in the csv is actually even better than xml! I will swipe it and commence those edits on Monday. Thanks for doing this work.

**Comment by JoshData** [comment]
I put the bioguide/opensecrets IDs right into the YAML.

**Comment by handlers** [comment]
Senate committee assignments:

http://www.republican.senate.gov/public/index.cfm/blog?ID=cccbb684-0ead-473b-8f51-2f5dee96acb2
http://democrats.senate.gov/committees/#%2EVJoOsB0MBg

I'll get going on them ASAP.

**Comment by handlers** [comment]
Some committee updates:

It looks like the Senate has XML for committees but not subcommittees right now.That results in [this ugly branch](https://github.com/unitedstates/congress-legislators/tree/committees) in which we lose subcommittee data. The first commit is just stripping out retired members from `committee-membership-current.yaml`; the second is the output of a scrape of the Senate committee XML. If anyone has opinions on whether or not to merge, I am all ears.

On the House side, we're waiting for clerk.house.gov to update their [committee information pages](http://clerk.house.gov/committee_info/index.aspx?comcode=BA00). I spoke to them about this [committee assignments table](http://clerk.house.gov/committee_info/oal.aspx) and they said they were waiting on the House Speaker's office for the data. I presume that's also true of the more committee-specific pages as well.

**Comment by JoshData** [comment]
I'm OK with merging partial data.

I've wiped all of the committee membership info from GovTrack in the meanwhile so as not to report anything that's no longer true. I'll wait until we have fresh data from the House before pulling any of it in.

**Comment by handlers** [comment]
See #250, where I've collected most committee memberships for the 114th Congress.
