### ISSUE TITLE
Dave Camp still shows as head of Ways and Means in committee-membership-current

### ISSUE THREAD

**Issue by bcdebusk** [unitedstates/congress-legislators#242]
Or am I misreading it?  It shows Paul Ryan as a member and Dave Camp as Chair.

**Comment by JoshData** [comment]
I think we're paused on committees because the data from the House and Senate are incomplete. See the bottom of #223.

**Comment by bcdebusk** [comment]
Ahhh... thank you for the explanation.  I'll wait until it's all sorted out and then re-upload.

It seemed strange that Lamar Alexander was still the minority ranking member of HELP as well.

**Comment by JoshData** [comment]
Pretty sure this was solved long ago.
