### ISSUE TITLE
Mike Rogers showing-up under two different Thomas IDs

### ISSUE THREAD

**Issue by bcdebusk** [unitedstates/congress-legislators#243]
He's under 01704 and 01651.  And the bioguides are different as well, but do correspond with their respective Thomas IDs.

**Comment by JoshData** [comment]
They are two different individuals. ;-)

On February 8, 2015 5:41:23 PM EST, Brian DeBusk <notifications@github.com> wrote:
>He's under 01704 and 01651.  And the bioguides are different as well,
>but do correspond with their respective Thomas IDs.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/unitedstates/congress-legislators/issues/243

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bcdebusk** [comment]
Yet the legislators file only list one -- the 01704 member.

**Comment by JoshData** [comment]
There are two legislators files. (One of the two Mike's is no longer serving.)
