### ISSUE TITLE
Add 'Instagram' field to legislators-social-media.yaml?

### ISSUE THREAD

**Issue by nickom** [unitedstates/congress-legislators#245]
In going through the official sites of the 114th Congress, I've noticed that quite a few link to official Instagram accounts. Worth adding this field?

Some examples all linked from senate.gov sites:
http://instagram.com/sencorygardner
http://instagram.com/senmikelee
http://instagram.com/senjohnmccain
http://instagram.com/wydenpress
http://instagram.com/senatorrandpaul
http://instagram.com/clairecmc

**Comment by JoshData** [comment]
Fine by me.

**Comment by nickom** [comment]
:+1:  just spoke with @handlers and he's going to add that field in the next scrape of house.gov/senate.gov sites for social media accounts.

Thanks!
