### ISSUE TITLE
MapLight IDs

### ISSUE THREAD

**Issue by mrumsky** [unitedstates/congress-legislators#274]
Hey everybody! Michael Ruvinsky, database manager for MapLight here. 

We'd like to change the "maplight" IDs found in **legislators-current.yaml** and **legislators-historical.yaml**. Confusingly, MapLight uses two different sets of IDs for politicians (one for candidates, another for legislators), and the IDs that were added to the files [back in 2013](https://github.com/unitedstates/congress-legislators/pull/99) actually aren't the ones that can be used to look up a legislator on our site. We'd like to replace the IDs in the files now with ones that can be used in our urls (e.g. http://maplight.org/us-congress/legislator/567).

Would anyone have a problem with us changing the values of the "maplight" IDs? Is anyone currently using those IDs?

Many thanks to @h4ck3rm1k3 for adding them two years ago!

**Comment by h4ck3rm1k3** [comment]
I have some code for doing what I did. https://github.com/electionr/rootstrikers-wikipedia/blob/master/maplight_name.py https://github.com/electionr/rootstrikers-wikipedia/blob/master/maplight_convert2.py https://github.com/electionr/rootstrikers-wikipedia/blob/master/maplight_convert.py

**Comment by mrumsky** [comment]
Submitted pull request #288
