### ISSUE TITLE
house minority offices

### ISSUE THREAD

**Issue by timball** [unitedstates/congress-legislators#283]
currently committees-current.yaml does not include house minority office urls . there's a field for minority_rss_url but that's not the same and does not capture that data . 

proposal is to EITHER add a field called `minority-url:` OR give minority committees their own entry . current system not capturing everything . since some entries already have a `minority_rss_url:` i'm gonna go w/ the first option .

PR coming soon . 

--timball

**Comment by timball** [comment]
hrm ... if i want to split up PR's i have to make branches don't i ... womp womp . sorry about that . didn't do that . 

--timball

**Comment by nickom** [comment]
I just remembered we discussed adding a `minority_url` field for committees back in July, 2013, but I never got around to making the pull request: https://github.com/unitedstates/congress-legislators/issues/108#issue-16829270

cc @konklone

**Comment by JoshData** [comment]
Let's take this conversation back to #108 and close this one.
