### ISSUE TITLE
Missing legislators in 'legislators-historical.yaml' ?

### ISSUE THREAD

**Issue by smoser11** [unitedstates/congress-legislators#287]
I’m sorry if this is not the appropriate channel by which to communicate (sorry, I’m a novice) but I wanted to write as ask how it is that a legislator comes to be in either ‘legislators-historical.yaml’ or ‘legislators-current.yaml’.   

 I think there are a few hundred missing legislators. When I count up the number of records in ‘legislators-current.yaml’ and ‘legislators-historical.yaml’ I get a total of 12347 legislators (as of 19 May 2015). However, when I scrape bioguide.congress.gov myself, I get 12671 legislators . For example, John WIlliams ( http://bioguide.congress.gov/scripts/biodisplay.pl?index=W000515) doesn’t appear in the yamls (but a John Williams with bioguide ID of W000513 does).  Phillips White (http://bioguide.congress.gov/scripts/biodisplay.pl?index=W000388 ) doesn't appear in the yaml files, either.  Is this an issue of members serving in the Continental Congress?

 Can I ask how the yaml files got made originally?

Sorry for my ignorance, and thanks.

Scott

**Comment by JoshData** [comment]
Hello,

> I’m sorry if this is not the appropriate channel by which to communicate 

It is!

> John WIlliams...doesn’t appear in the yamls 

We don't include people who only served in the Continental Congress. As the documentation says in a couple of places, we include members of the United States Congress (i.e. 1789-present).

> Can I ask how the yaml files got made originally?

The files were originally created by scraping the bioguide. Today they are maintained by hand (with the help of various scripts in the scripts directory).

I'll leave the issue open if you have other questions --- please close it if this resolves things. :)

**Comment by smoser11** [comment]
My apologies.  Many thanks for the clarification.  Sorry again.
