### ISSUE TITLE
Make sure House/Senate websites use the domain root

### ISSUE THREAD

**Issue by konklone** [unitedstates/congress-legislators#300]
Instead of what they redirect to. @gmj2053 has identified 1 to 3 examples (including Crenshaw) of us using a particular index-y URL as the homepage for a member, which can break.

**Comment by gmj2053** [comment]
https://conyers.house.gov/index.cfm/home
https://hurt.house.gov/index.cfm/home
https://noem.house.gov/index.cfm/home
https://poe.house.gov/home
https://renacci.house.gov/index.cfm/home
https://sessions.house.gov/index.cfm/home
https://sinema.house.gov/index.cfm/home
https://katherineclark.house.gov/index.cfm/home
https://dold.house.gov/home

**Comment by konklone** [comment]
So we use http://www.house.gov/representatives/ as our source, which sometimes uses the specific index page URL as the homepage, as you've noted.

I think the House has fully standardized on subdomains now, and we'd be fine chopping off URLs and expecting the subdomain to redirect. I'll submit a PR to do that.
