### ISSUE TITLE
Facebook Graph API no longer supports lookup by username

### ISSUE THREAD

**Issue by dannguyen** [unitedstates/congress-legislators#306]
Facebook no longer provides the `username` in the API:
- https://developers.facebook.com/docs/apps/changelog#v2_0_graph_api
- http://stackoverflow.com/questions/23428498/get-username-field-in-facebook-graph-api-2-0

This means that [resolvefb() in scripts/social_media.py](https://github.com/unitedstates/congress-legislators/blob/master/scripts/social_media.py#L127) will have to be overhauled. I can try a pull request later...I don't think it's a huge problem overall.

**Comment by SiddDev** [comment]
nice find @dannguyen

**Comment by joelcollinsdc** [comment]
My best googling has not turned up a way to get user ids from usernames in facebook without violating some kind of scraping ToS.  I understand that storing user IDs is valuable to detect username changes, but it adds complexity as well.  Is it worth keeping facebook IDs around?

**Comment by JoshData** [comment]
I'm not using the ID field, so dropping it is fine with me.

**Comment by dwillis** [comment]
Same.

**Comment by joelcollinsdc** [comment]
For all services?  having twitter id was moderately useful for catching renames...

**Comment by JoshData** [comment]
I just meant the FB ID. (I'm not using the Twitter ID either, but if it remains useful in the scripts then there's no reason to drop it.)

**Comment by konklone** [comment]
:+1: Merged #444.
