### ISSUE TITLE
rohrabacher social media sites

### ISSUE THREAD

**Issue by gmj2053** [unitedstates/congress-legislators#308]
we have
http://www.youtube.com/channel/UCFr7qO61vGJyyBJ7B_gB1_Q
http://www.facebook.com/danarohrabacher
for rohrabacher that I don't see in my feed of your data.

**Comment by luzbrillante** [comment]
no eres Gina la exnobia de juan leal ..que vives en delano california? yo soy Gloria 

Enviado desde mi teléfono Verizon Wireless

-----Mensaje original-----
De: Gina Jones <notifications@github.com>
Para: unitedstates/congress-legislators <congress-legislators@noreply.github.com>
Enviado: mié, ago 19, 2015 20:47:35 GMT+00:00
Asunto: [congress-legislators] rohrabacher social media sites (#308)

we have
http://www.youtube.com/channel/UCFr7qO61vGJyyBJ7B_gB1_Q
http://www.facebook.com/danarohrabacher
for rohrabacher that I don't see in my feed of your data.



---
Reply to this email directly or view it on GitHub:
https://github.com/unitedstates/congress-legislators/issues/308

**Comment by konklone** [comment]
https://www.facebook.com/danarohrabacher isn't linked to from the Congressperson's [official site](https://rohrabacher.house.gov/), and appears to be affiliated with the campaign, not the office.

The YouTube account, on the other hand, looks official and is embedded on the official homepage. I amde #309 to address this, and am closing this issue in favor of that one.

Thank you for reporting!

**Comment by luzbrillante** [comment]
¡Chatea conmigo en la aplicación renovada de Yahoo Messenger! Puedes compartir múltiples fotos y videos al instante, enviar archivos GIF animados e incluso cancelar el envío de tus mensajes. Disponible gratis en Android, iPhone, la Web y Yahoo Mail.

¡Obtén Yahoo Messenger ahora! https://yho.com/inviteym2




Enviado desde mi Verizon Wireless 4G LTE Smartphone
