### ISSUE TITLE
Add ID/url segments for congress.gov?

### ISSUE THREAD

**Issue by dwillis** [unitedstates/congress-legislators#320]
Member pages on Congress.gov have two url segments individual to the member (an example: https://www.congress.gov/member/james-abdnor/A000009). The second is the bioguide ID, but the first is a slug based on the name. Any objection to adding it to the list of IDs we have? Perhaps call it "congress_gov_id"?

**Comment by JoshData** [comment]
It's not necessary to make a working link (e.g. https://www.congress.gov/member/abdnor/A000009 or most any string between the slashes works too), btw.

**Comment by dwillis** [comment]
Ah, ok.
