### ISSUE TITLE
Legislative term dates for some Members of Congress overlap

### ISSUE THREAD

**Issue by geoffharcourt** [unitedstates/congress-legislators#326]
From a scan of the data, it looks as if the end date of their term is one day before the start of the new Congress. However, for the end of the 106th Congress and the start of the 107th Congress, they have dates that overlap (MoCs of the 106th have their end date as 1/3/2001, MoCs of the 107th have their start date as 1/3/2001).

From a quick check of the data, this looks like the biggest hurdle to these dates having referential integrity and not overlapping (with a Member only holding one term on any particular day). Would you accept a PR to manually update those particular dates?

**Comment by JoshData** [comment]
It's actually correct. Terms begin & end on noon on January 3rds. See #305 for the most recent discussion about this. Note that our `end` field is for the constitutional end of the term, while our `start` field is the date a Member was sworn in.

**Comment by geoffharcourt** [comment]
Thanks for the explanation.
