### ISSUE TITLE
Boehner retirement

### ISSUE THREAD

**Issue by joelcollinsdc** [unitedstates/congress-legislators#328]
Is running retire.py sufficient?   

https://github.com/joelcollinsdc/congress-legislators/commit/8e3da14ebabe2100da73f118b5b9ddda2063d587

**Comment by joelcollinsdc** [comment]
Also adding ryan to leadership roles section

https://github.com/joelcollinsdc/congress-legislators/commit/3c16e241f6629c3301722ddda281284b7adccffa

I did these by hand... anything else i'm missing?

**Comment by konklone** [comment]
This looks right to me. @JoshData can you think of anything else?

@joelcollinsdc In any case, feel free to open these as PRs, it's okay to open a PR before it's finalized. Want to open a PR now?

**Comment by JoshData** [comment]
Looks great!

**Comment by joelcollinsdc** [comment]
thanks, submitted PR
