### ISSUE TITLE
Missing Data From https://www.govtrack.us/api/v2/role?current=true

### ISSUE THREAD

**Issue by haithemaraissia** [unitedstates/congress-legislators#330]
Hi,
The https://www.govtrack.us/api/v2/role?current=true was getting all the correct information.
But, today the node of speaker of House is missing.
Is there any update on when the data will be updated.
Thank you

**Comment by JoshData** [comment]
Issues with the GovTrack API should be asked on the GovTrack mail list:

https://www.govtrack.us/developers

(unless you are sure the problem originates in this repository, which I don't think this does). Thanks.

**Comment by konklone** [comment]
It's not because we merged #329?

**Comment by JoshData** [comment]
The merge is (I believe) correct & I pulled the update into GovTrack this morning & the data showing on GovTrack appears to be updated/correct.

**Comment by haithemaraissia** [comment]
Greeting to everyone and thank you for addressing this issue:

-JoshData
I will submit my question as you pointed to the Mail List.

However, i 'm absolutely sure that the speaker of the house node is missing from this :https://www.govtrack.us/api/v2/role?current=true 

If you parse this url to the browser, you can see that you can't find the Speaker of house node. 

Maybe you're saying the data local to your computer. But, from Outside IP , we really don't see the full list.

Note:
Few days ago, i was seeing it. But, i don't know if there was merge or overwrite that had erased that note.

We really appreciate your help.
https://www.govtrack.us/api/v2/role?current=true 
( Speaker of house node is no longer present)

Thank you .

**Comment by JoshData** [comment]
@haithemaraissia And I'd be glad to respond to your question if you ask it in the right place. This space on github is not about GovTrack.

**Comment by haithemaraissia** [comment]
Thank you JoshData. I will posted it in the Mail List group.
