### ISSUE TITLE
Missing FEC IDs in YAML file for freshmen senators previously in House

### ISSUE THREAD

**Issue by corbyhobbs** [unitedstates/congress-legislators#332]
(Posting this here on the advice of Josh)

I was looking through the legislators-current.yaml file and came across some instances where senators elected in 2014 who were previously representatives are missing their senate FEC candidate IDs. After looking through the file, the list of senators I found like this are:

Cotton - S4AR00103
Gardner - S4CO00395
Lankford - S4OK00232
Cassidy - S4LA00107
Peters - S4MI00355

Thought you'd want to know.

Thanks!
Corby

**Comment by mrumsky** [comment]
Thanks for noticing this, @corbyhobbs! I'll make this change and submit a pull request.

**Comment by mrumsky** [comment]
Added (#317)
