### ISSUE TITLE
Wrong format in committees-current.yaml

### ISSUE THREAD

**Issue by torresjorge** [unitedstates/congress-legislators#333]
I found some issues on the file, instead of - name is pointing to - thomas_id, is this correct?

  - name: Immigration and the National Interest
    thomas_id: '04'
    wikipedia: United States Senate Judiciary Subcommittee on Immigration, Refugees
      and Border Security
  - thomas_id: '24'
    name: Bankruptcy and the Courts
  - thomas_id: '25'
    name: Oversight, Agency Action, Federal Rights and Federal Courts
  wikipedia: United States Senate Committee on the Judiciary...

**Comment by bashar007** [comment]
["markdown","md","mkd"],"text/x-nfo":["nfo"],"text/x-opml":["opml"],"text/x-pascal":["p","pas"],"text/x-sass":["sass"],"text/x-scss":["scss"],"text/x-setext":["etx"],"text/x-sfv":["sfv"],"text

**Comment by JoshData** [comment]
These are semantically equivalent in YAML.
