### ISSUE TITLE
Querying Bills - Why aren't the voter and voter_ids represented as arrays in the JSON?

### ISSUE THREAD

**Issue by mekinney** [unitedstates/congress-legislators#337]
This is a pretty fundamental question, but why aren't the voter and voter_ids returned from bills queries formatted as arrays in the returned JSON?  It seems the way it is currently structured, it's using values (for example the bioguide_"A000374") as a string identifying a value.

I know any change to this would be huge because of the all the clients currently using it, however, it's making the automating parsing of the return results more challenging.  The way it's formatted now, the parser has to know the meaning of the result as opposed to simply the format.

I haven't gone through the rest of the API to see if there are other examples of this.

Thanks in advance,
Mike

Example current voter_ids snippet:
      "voter_ids": {
        "A000374": "Nay",
        "A000370": "Yea",
        "A000055": "Nay",
        "A000371": "Yea",
        "A000372": "Nay",
        "A000367": "Nay",...

Example current voters snippet:
      "voters": {
        "A000374": {
          "vote": "Nay",
          "voter": {
            "bioguide_id": "A000374",
            "birthday": "1954-09-16",
...
         }
        },
        "Z000018": {
          "vote": "Nay",
          "voter": {
            "bioguide_id": "Z000018",
            "birthday": "1961-11-01",
            "chamber": "house",
...

**Comment by konklone** [comment]
The primary reason it was this way was to allow people to use the partial responses feature to only get individual MoCs' voting information, so you could ask for a field like `voters.A000374` and get only that person's vote. 

It definitely has some downsides (for example, it makes Elasticsearch schemas wildly huge), and (when I worked for Sunlight) I considered changing this, but massive arrays have issues too.The [Congress app](http://congress.sunlightfoundation.com/) for Android (the animating application for earlier versions of the API) used this feature to efficiently retrieve data in a mobile context.

**Comment by mekinney** [comment]
Thank you.  After working with the data more, it makes sense and works well.  Sometimes my old school procedural thinking gets in my way. :)

**Comment by konklone** [comment]
Glad to hear it!
