### ISSUE TITLE
bioguide_id "M000317" does not exist

### ISSUE THREAD

**Issue by rapcal** [unitedstates/congress-legislators#338]
It represents Rep. Kathryn McCarthy, which married after election and served under the name Kathryn O'Loughlin McCarthy. She's now tied to bioguide_id O000081.

http://bioguide.congress.gov/scripts/biodisplay.pl?index=O000081
http://bioguide.congress.gov/scripts/biodisplay.pl?index=M000317

**Comment by rapcal** [comment]
Sorry. Getting M000317 with sunlight foundation API but saw it was fixed years ago here... :-S

**Comment by konklone** [comment]
> Sorry. Getting M000317 with sunlight foundation API but saw it was fixed years ago here... :-S

:-S
