### ISSUE TITLE
Robert Menendez - bioguide_id M000639 - name and aliases are Men,ndez

### ISSUE THREAD

**Issue by mekinney** [unitedstates/congress-legislators#339]
It looks like Robert Menendez's last name is incorrect in the database:
Men,ndez instead of Menendez

This is also a bit odd, because he is the only current legislator with an "other_names" property.  Below are a subset of the fields returned for him with the query: /legislators?per_page=all

      "bioguide_id": "M000639",
      "first_name": "Robert",
      "last_name": "Men‚ndez",
      "nickname": "Bob",
      "other_names": [ { "last": "Menendez" } ],

I can't find the other_names property in the API documentation.

**Comment by JoshData** [comment]
Wrong repository. Presumably => https://github.com/sunlightlabs/congress/issues

**Comment by mekinney** [comment]
Thank you.  I just realized that also.
