### ISSUE TITLE
Adding district office data

### ISSUE THREAD

**Issue by pmkane** [unitedstates/congress-legislators#343]
Hi all:

We're interested in adding district office data (in-state office addresses/phones/etc for Representatives and Senators) to the dataset.  Reviewing the existing YAML, I can't tell if the preferred approach is to add this data to a separate file (ala legislators-social-media.yaml) or to add it directly to legislators-current.yaml.

Thoughts?

**Comment by dwillis** [comment]
I think district office data would go in a separate file, but curious what others think.

**Comment by konklone** [comment]
I think it could work either way, though I am curious how much the data depends on the particular Rep or Senator in office. Do incoming members just take over the office space of the previous ones, or do they tend to close offices and open new ones?

**Comment by pmkane** [comment]
They open new offices, typically.  They are all leased directly by the Senator or Representative.

Since it sounds like there aren't strong feelings on it either way, we'll submit a pull request as a separate file.

Thanks.

**Comment by dwillis** [comment]
Well, redistricting can definitely change the office locations, and many senators move offices around upon being elected, so things can and do change. I don't think they change a lot, though. The reason I suggested a separate file is that I'm not sure that this info really needs to be in legislators-current.

**Comment by konklone** [comment]
> They open new offices, typically. They are all leased directly by the Senator or Representative.

Congress is weird.

> Since it sounds like there aren't strong feelings on it either way, we'll submit a pull request as a separate file.

:+1:

**Comment by joelcollinsdc** [comment]
@tcarobruce Incredible work.  Are there scripts that you used to gather the data?  How do you envision this is kept up to date?

**Comment by pmkane** [comment]
Hi Joel:

This is a district office database that was maintained by Congress Merge (www.congressmerge.com).  Michael Waters, the owner of Congress Merge, gave us permission to reformat it for congress-legislators and release it under CC license.

Keeping it up to date is an unsolved problem.

**Comment by JoshData** [comment]
All files in this project must be in the public domain. See https://github.com/unitedstates/congress-legislators/blob/master/CONTRIBUTING.md. CC licenses aren't acceptable, unfortunately.

I'm also :-1: on any data that has no update strategy.

**Comment by pmkane** [comment]
Hi Joshua:

Getting it released public domain instead isn't an issue.

But if it won't be accepted without an update strategy, then it's not worth
the round trip to the original vendor for the sign off. Hopefully adding
the data provided impetus, to either us or someone else, to track updates.

Let us know!

On Sunday, March 6, 2016, Joshua Tauberer <notifications@github.com> wrote:

> All files in this project must be in the public domain. See
> https://github.com/unitedstates/congress-legislators/blob/master/CONTRIBUTING.md.
> CC licenses aren't acceptable, unfortunately.
>
> I'm also [image: :-1:] on any data that has no update strategy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/unitedstates/congress-legislators/issues/343#issuecomment-192878631>
> .
>


-- 
Patrick Michael Kane
We Also Walk Dogs
<pmk@wawd.com>

**Comment by jtolds** [comment]
Okay almost a year later, new congress, and this is data I'm looking for! 

Does anyone know of a source for this data? 

I can write a screenscraper, but aside from votesmart.org (which I suppose I could pay for their API), I can't find a list of district offices anywhere. Have I missed something? @pmkane: how was your dataset from last year compiled? Manually researching each legislator's website?

It's a shame this isn't in the clerk.house.gov/senate.gov source XML.

**Comment by pmkane** [comment]
We mechanical turked it.  It'll be updated in our fork (https://github.com/TheWalkers/congress-legislators) in the near future.

**Comment by pmkane** [comment]
Most of the district offices are now available in our fork.  We'll update them as new data trickles in.

**Comment by jtolds** [comment]
Awesome! Thanks so much @pmkane!

**Comment by jlgoldman** [comment]
Just now discovered this thread, unfortunately after spending a few days this week building up a nearly identical data set specifically for district offices.

https://github.com/jlgoldman/membersofcongress

@pmkane Happy to have the Turk-ed fork be the authoritative source going forward and to help out where I can. If my data is useful or could be used as a sanity for the Turk-ed data I'm happy to help work on that.

Also I geocoded my data and published the latlngs, as well as used them as a sanity-check for address data, making sure the geocoded location belonged to the legislator's Congressional district polygon (for House reps). I can merge my geocodes with the Turk-ed data and/or add a geocoding script to that repo if there's interest in that.

My approach was to build a clipping tool that auto-parsed a block of address text into structured data when copy-pasted from a Congressional website. This meant that the manual work was limited to opening up a website and hunting for the addresses by eye, but structuring the data was automatic in about 90% of cases. This made it fast enough for me to collect all the data individually.

I was going to build a public-facing version of the clipping tool for maintaining the data set until I came across this thread. If there's still interest in that I'll build it; it's possible it could also be useful for the Turkers to significantly reduce the task time.

**Comment by pmkane** [comment]
Added geocoding would be lovely, if you're willing/able to add script.  Data improvements or corrections are also very welcome.

**Comment by joelcollinsdc** [comment]
Should we add links to related repositories in the README?  To me, managing separate but related repos seems like a good model for collecting data that isn't maintained in this repo.

**Comment by pmkane** [comment]
Fine by us, Joel. although our preference would be to see the data ingested into the parent for more visibility.

**Comment by JoshData** [comment]
+1 to links in the README.

**Comment by essandess** [comment]
@pmkane and others. The file [legislators-district-offices.yaml](../../../TheWalkers/congress-legislators/blob/master/legislators-district-offices.yaml) is a great addition -- thank you very much.

I've already used it along with this lookup script [congress_lookup.py](../../../essandess/congress-legislators/blob/master/scripts/congress_lookup.py) to access contact information relevant to me, e.g.:

```
congress_lookup.py --committee 'Senate*Financ' fax
"Senate Committee on Finance" member properties:
Property 'fax' for Orrin G. Hatch:
202-224-6331
...
```

I suggest tracking this with #362, as the YAML load time is ridiculously slow. That said, they also very easy to edit and correct, so it's a nice raw format. Mirroring an generated json for fast loads is a good idea.

**Comment by essandess** [comment]
The importance of including district office information is highlighted in this tweet:

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Second, writing a letter to the district office (state) is better than sending an email or writing a letter to DC.</p>&mdash; Emily Ellsworth (@editoremilye) <a href="https://twitter.com/editoremilye/status/797243719774707712">November 12, 2016</a></blockquote>

Full thread in the storify **[How to effectively talk to your member of congress](https://storify.com/editoremilye/i-worked-for-congress-for-six-years)**.

**Comment by jlgoldman** [comment]
Strongly agree with having json and other formats mirrored, both for load times and for ease of use by consumers. Feels like a non-programmer should be able to use this data as-is by slurping it into Excel via CSV for instance, without having to write a script to do so. That was my philosophy at https://github.com/jlgoldman/membersofcongress where I mirrored the data to several formats, where the mirrored files are generated almost instantaneously via a one-line script invocation.

If there is interest here and no concerns about maintenance, I'm happy to add script to the fork with district office data (https://github.com/TheWalkers/congress-legislators) that mirrors the district offices to json and optionally other formats.

**Comment by essandess** [comment]
FYI, YAML load speeds are improved by 10x if the fast C Loader is used:

```python
%timeit y = open('legislators-current.yaml','r'); foo = yaml.load(y)
1 loop, best of 3: 7.96 s per loop

%timeit y = open('legislators-current.yaml','r'); foo = yaml.load(y, Loader=yaml.CLoader)
1 loop, best of 3: 976 ms per loop
```

I've updated my own [lookup code](../../../essandess/congress-legislators/blob/master/scripts/congress_lookup.py) to use this option.

There's still another 3x to squeeze if json's were used, but at least the largest YAML file can be loaded in under a second.

```python
y = open('legislators-current.yaml','r'); data = yaml.load(y,Loader=yamlCLoader)
j = open('legislators-current.json','w'); json.dump(data,j); j.close()
%timeit j = open('legislators-current.json','r'); jdata = json.load(j)
10 loops, best of 3: 37.1 ms per loop
```

**Comment by konklone** [comment]
Mechanical Turk is an update strategy, IMO, and this is a major and frequently requested data set. I get personal DMs asking me for this, even.

I would like to accept this data, especially if the people most invested in it are a :+1: on re-Turking it on a regular-ish basis to keep it up to date.

**Comment by TheWalkers** [comment]
If it'll be accepted, happy to resubmit a PR.

**Comment by JoshData** [comment]
I'm really at peak capacity here and really can't handle this repo becoming more complicated unless it comes with a way for me to do less work here.

**Comment by TheWalkers** [comment]
Fine by us. We'll continue to maintain in our fork then.

**Comment by essandess** [comment]
Here's another item on why the district data is important, whether the district data is parsed by BeautifulSoup or Turked:

> **[Here’s Why You Should Call, Not Email, Your Legislators](https://www.nytimes.com/2016/11/22/us/politics/heres-why-you-should-call-not-email-your-legislators.html)**

I've also been told that:

> Congressional staffers and legislators repeatedly say that when an office is inundated with calls from constituents, they respond

**Comment by konklone** [comment]
@JoshData if the district office data was in a separate file, and others kept it up to date, would that be a complexity tax on your work?

**Comment by JoshData** [comment]
Yes.

**Comment by essandess** [comment]
Relevant: **[Apps Make Pestering Congress So Easy That Politicians Can't Keep Up](https://www.wired.com/2017/01/apps-make-pestering-congress-easy-cant-keep/)**. This and related repo's and their authors are cited.

> The consensus among activists and staffers alike is phone calls are better than email, and that showing up in person to district offices or town halls is better than phone calls. But email and social media make a difference too, as long as those communications are personalized.

This speaks to the importance of including both the fax data and the district data, which both facilitate personalized correspondence.

**Comment by cldwalker** [comment]
As a [downstream provider](https://www.callcongressnow.org/) of calling data, local district data is our top feature request. People are not consistently able to contact their reps at the federal level anymore and really could use this info

> I'm really at peak capacity here and really can't handle this repo becoming more complicated unless it comes with a way for me to do less work here.

@joshdata Since [having others maintain this data](https://github.com/unitedstates/congress-legislators/issues/343#issuecomment-275852543) is too costly, is there anything we could specifically do to make this possible? There's enough goodwill and interest that even asking for help on other issues to free you up may be a possibility

**Comment by atbaker** [comment]
Hi folks,

First, @JoshData and @konklone - THANK YOU for all the work you've done to maintain this repo. It's an incredible resource and I know that's because of countless hours of effort from you both.

I'm also interested in district office data and I have one proposal for how we could do it.

I spent a little time today building scrapy spiders for the `*.house.gov` sites. Scraping them outright is pretty daunting and the spiders would be pretty brittle in the end.

But scraping might be good enough just to alert us when this data changes. If we stored and recorded one concatenated string for each rep's list of offices, we could run the scrape weekly and identify which reps have updated their info.

It's still not perfect - when we discover changes, they'll need to be manually updated. And we'll need a URL for each rep's offices page + an xpath for the div with office data.

I'm willing to put together a PR next weekend if you all think it's worth exploring.

Thanks.

**Comment by JoshData** [comment]
@atbaker Please get in touch with the other folks in this thread who are already working on it.

@cldwalker Where is the work on district data currently taking place?

**Comment by konklone** [comment]
As a note, the fork at https://github.com/thewalkers/congress-legislators is now being used for this API, run by @woodhull and crew:

http://developers.visitthem.org

The data continues to be visibly maintained, and I think it would be good for us to capture the energy around district office information going into the 2018 and 2020 cycles.

@TheWalker @cdwalker looking at the diff between your fork and our repo, it looks like it's two Python scripts and `legislators-district-offices.yaml` (and a stray data change to add a trailing slash to a member URL for some reason):

https://github.com/unitedstates/congress-legislators/compare/master...TheWalkers:master

Can you speak a little bit to the level of maintenance and handholding you have to perform to keep the data up to date?

**Comment by jlev** [comment]
I also use the TheWalkers fork, because district data is so useful for [CallPower](https://github.com/spacedogXYZ/call-power). I also maintain a zipcode to congressional district [dataset](https://github.com/spacedogXYZ/us_zipcodes_congress), to more easily match callers with their reps.

For maintenance and updates, you may want to ask @pmkane or @tcarobruce. They get PRs from other downstream users pretty regularly.

**Comment by pmkane** [comment]
I'd still be psyched to see this integrated into the core repo, or, at the very least, referenced in the README.md, so folks don't have to either be "in the know" or wade through this issue to figure out where to get this important data.

We are in maintenance mode at this point.  We are not scraping to look for new offices or offices that have gone dark, but we welcome, and have been incorporating, tweaks and improvements from users.  Some of those come from [ActionKit.com](www.actionkit.com) customers who submit support tickets, some of it via GitHub pull requests.  In general, the data seems very solid and dozens of groups on ActionKit have turned people out to local offices without complaint.

Unless someone else wants to take this over, we will do another full pass after the next election.

**Comment by woodhull** [comment]
Just chiming in to endorse the idea of getting this data incorporated. We also have customers organizing their members using the data (and sending occasional fixes) so I think it's increasingly solid at this point.  I think I only discovered @TheWalkers data set because @jlev commented on a facebook post of mine musing about how such data might be collected. Getting a link into the README or even better the data accepted upstream would help access to this info be more broadly accessible to people with less knowledgeable facebook friends.

**Comment by JoshData** [comment]
I'm :+1: to adding district data now with:

* a clean PR, that includes
* documentation
* tests (hooked into both Travis and CircleCI (until we decide CircleCI has taken over for Travis))
* and works with the automatic push to the gh-pages branch for publication

**Comment by konklone** [comment]
@TheWalkers Would you be up for doing what @JoshData describes? I'm happy to assist if it helps.

**Comment by pmkane** [comment]
We can probably do some docs in the relatively near future, but tests and integrating with gh-pages isn't likely to rise to the top of our list soon.  So if you were willing to take one or both of those, @konklone, that would be lovely.

If that's a viable path forward, I'd like some guidance on where the docs should live.  Right now, it looks like everything is in README.MD.  Is that where docs on this should go as well?

**Comment by JoshData** [comment]
gh-pages integration will probably "just work," but I mentioned it because someone has to be on the hook for making sure it does.

Putting docs in the README works for me.

**Comment by woodhull** [comment]
Can we close this, since the data has been merged?
