### ISSUE TITLE
Issues with legislators-current csv data

### ISSUE THREAD

**Issue by sashaperigo** [unitedstates/congress-legislators#361]
I found my way to this repo after downloading the <a href="https://www.govtrack.us/data/congress-legislators/legislators-current.csv">legislators-current.csv</a> file in the <a href="https://www.govtrack.us/data/congress-legislators/">GovTrack open data repository</a>. The data is very thorough, but unfortunately, it's pretty difficult to use because a significant percent of the columns are misaligned.

Two causes of this that I noticed are:

- ***Errors scraping contact and RSS feed URLS***
<br />In the rows for some legislators, URL parameters like "format=raw" or "type=rss" have ended up in their own cell, causing the remaining cells in the row to be shifted over a column.
- ***Errors scraping addresses***
<br />Some addresses end up getting split up over two columns, and the city, state and zip code end up in the phone column, shifting the remaining cells over.

If you could fix these two issues it would make the data infinitely easier to use!

**Comment by JoshData** [comment]
Hello. The conversion from YAML (the files here) to CSV (on GovTrack) is done by https://github.com/unitedstates/congress-legislators/blob/master/scripts/alternate_bulk_formats.py (in this repo). 

Can you point out a particular line that you think is misformatted?

I am extremely overloaded at the moment so I am not likely going to be able to look closer in the near future. Maybe someone else will be able to help.

**Comment by sashaperigo** [comment]
Hi! Apologies for the delayed response. I'm looking into this now and will let you know what I find.

**Comment by sashaperigo** [comment]
Wow, I'm sorry about this! I don't know what I'd done to my CSV before, but I can't reproduce this. Everything looks fne with the script and the .csv file in the open data repository.
