### ISSUE TITLE
Remove WaPo id

### ISSUE THREAD

**Issue by thinkcontext** [unitedstates/congress-legislators#368]
As far as I can tell the Washington Post ids are not supported by the WaPo.  The Post doesn't offer any public api which can use them.  I tried searching for the first 5 entries in the legislators file and no results came up when filtering by topic.  I also tried manually plugging the ids into working topic urls and got no results.  

I'd be happy to submit a patch that removes them.

**Comment by dwillis** [comment]
+1 to this.

**Comment by JoshData** [comment]
Ok by me.

**Comment by JoshData** [comment]
The README needs to be updated in a few places.

**Comment by dwillis** [comment]
README updated 62380a6243bb891732d32e5a67cb9571bc9770b8

**Comment by JoshData** [comment]
TY!

**Comment by JoshData** [comment]
These IDs are still in the legislators-historical file. Someone should remove them and then update https://github.com/unitedstates/congress-legislators/blob/master/test/validate.py#L37.
