### ISSUE TITLE
New House members sworn in

### ISSUE THREAD

**Issue by JoshData** [unitedstates/congress-legislators#378]
I think at least one new member of the House was sworn in today, to fill a vacancy. I usually handle this but I'm a little swamped tomorrow so if anyone else can figure out what happened I'd appreciate it. :)

**Comment by dwillis** [comment]
Three of them, in fact. I'll get on it.

**Comment by dwillis** [comment]
I've added the two new folks: James Comer of KY & Dwight Evans of PA, plus moved over Colleen Hanabusa of HI from historical file.

**Comment by JoshData** [comment]
Thanks! I've added their govtrack ids.
