### ISSUE TITLE
Question: How did you arrive at DK for Dakota Territory and OL for Orleans Territory?

### ISSUE THREAD

**Issue by jpmckinney** [unitedstates/congress-legislators#382]
https://github.com/unitedstates/congress-legislators/blob/master/scripts/utils.py#L62-L63

The [historical evidence](https://github.com/opencivicdata/ocd-division-ids/issues/136) I can find is that the abbreviations were DT and OT, which is what I'm recommending for Open Civic Data Division IDs.

**Comment by JoshData** [comment]
Hey James. I don't have any particular recollection (the records here go back to work I did around 2009) but it was probably from the keys in the drop-down at http://bioguide.congress.gov/biosearch/biosearch.asp.

Two-letter postal abbreviations were invented after the territories ceased to exist, so I don't think there is much to look at for standardization.

**Comment by jpmckinney** [comment]
Ah, thanks! Although the USPO/USPS only standardized abbreviations later, some were used nonetheless (e.g. on surviving letters and other records). I wonder how Bioguide chose those abbreviations.
