### ISSUE TITLE
Missing LIS Ids, Causing Votes Scanner to Fail

### ISSUE THREAD

**Issue by swt83** [unitedstates/congress-legislators#396]
Throwing this out while I continue to debug, but it looks like the LIS id is missing for the following Senators:

```
Vote could not find legislator "S389"!
Vote could not find legislator "S391"!
Vote could not find legislator "S385"!
Vote could not find legislator "S386"!
Vote could not find legislator "S387"!
Vote could not find legislator "S388"!
Vote could not find legislator "S390"!
```

This is output from my own script which takes the votes data and applies it to members.  Votes for the House have a ``bioguide_id`` and votes for the Senate have a ``lis_id``.  These are failing because they cannot be found.

**Comment by JoshData** [comment]
We have a script for this -- see the commit. Fixed. Thanks.

**Comment by swt83** [comment]
Thank you, sir.
