### ISSUE TITLE
[META] Discussion on types of data to include in this repo versus a related repo

### ISSUE THREAD

**Issue by joelcollinsdc** [unitedstates/congress-legislators#408]
Wanted to get a discussion going around what kinds of data should be included in this repo versus encouraging that data to be kept in a separate repository.  There have been a few great recommendations / contributions lately that are still open because maintainers have expressed reservations about including directly into this repo.  Its probably not fair to contributors to not have a policy about what work will or will not be included directly in here.

Here are a few that have come up recently that could potentially be separate repos:
#362 (Creating a json mirror of the YAML files)
#343 (including district office data which is currently mechanical turk'd)
data access scripts like #405 

My guess is the maintainers have concerns that the bigger this repo gets, the harder it will be to keep its quality high.  On the other hand, data that is not in the parent repository is harder to keep in sync and have high visibility.

My recommendation would be to put guidelines high up on the README that outlines what kinds of data should be here and how to find and include related data, and list out all other repositories that contain data or code not directly included here.  Hopefully, repositories containing related data use a consistent format and foreign keys.  

Repos like unitedstates/congress use git submodules to reference this data which would probably be my recommendation for other repos as well, but there are probably other ways to do this too.

**Comment by konklone** [comment]
@joelcollinsdc Thank you for raising these -- super timely, and IMO all 3 of these could and should be part of the project. The demand is clear, and the burden is minimal.

**Comment by JoshData** [comment]
i'm really not into seeing any new data added to this repo unless the folks adding new data are going to pitch in to closing the existing open issues first.

Listing related resources from our README sounds great to me. (Using git submodules is probably a bad idea - their use is discouraged because of security issues and other practical issues.)

**Comment by joelcollinsdc** [comment]
I'll go through and close out some dead issues, been on my todo list for a while.

Would a compromise be to have agreement that data like district office data doesn't need to be updated in step with the main data files?  And keep any maintenance scripts for them separate?

**Comment by JoshData** [comment]
It's the issues that are a problem because I can't preemptively mute issues about it, and in the long run when the data stops being maintained (because let's face we're losing institutional members of our community, rather than gaining them) then it's going to fall to the core maintainers anyway.

**Comment by mininternet** [comment]
@JoshData - surprised to hear you're losing members, especially in current political climate. Are there any outreach efforts, or ways us external developers could assist?

**Comment by jiagengliu** [comment]
I wonder whether it'd be good to include legislators' popular personal twitter accounts, e.g. @TiberiPress (empty account) vs @PatTiberi (constantly updating), and @SenRubioPress (30K followers) vs @marcorubio (1.88M followers).

**Comment by konklone** [comment]
@jiagengliu That comes up a lot, but I continue to think it's better to keep that out of scope of this repository.

One compromise might be to keep the district office file in a separate repo, but in the `@unitedstates` organization. If @TheWalker thought that integration with the congress-legislators repo would still be easy enough, we could pursue that at least as an interim solution.

I'm really impressed with [the district office data collected so far](https://github.com/TheWalkers/congress-legislators/blob/master/legislators-district-offices.yaml).

**Comment by joelcollinsdc** [comment]
#343 and #405 have been merged already, so I guess this has been answered, and the json/yaml discussion can happen in that thread
