### ISSUE TITLE
Senate contact xml has several bad website urls

### ISSUE THREAD

**Issue by thinkcontext** [unitedstates/congress-legislators#415]
The xml file provided by the Senate has 6 website urls that lack 'http:', ie:

    <website>//www.kennedy.senate.gov</website>

Its not clear to me whether this is intentional or not but it is causing the contact script to not include a website for those members.

**Comment by JoshData** [comment]
I've asked Arin at the Senate about fixing the XML file.

**Comment by JoshData** [comment]
Upstream data was corrected, big thanks to the Senate for a fast response.
