### ISSUE TITLE
Missing information for Kamala Harris from California

### ISSUE THREAD

**Issue by mattcassinelli** [unitedstates/congress-legislators#418]
twitter: @kamalaharris
Facebook: https://www.facebook.com/KamalaHarris/

**Comment by joelcollinsdc** [comment]
Hello, these are the campaign accounts (they link to kamalaharris.org).  This repo tracks only official government social media accounts (funded by taxpayers).

**Comment by joelcollinsdc** [comment]
FYI I found this page via google and it seemed pretty up to date..

http://www.socialseer.com/resources/us-senator-twitter-accounts/

**Comment by konklone** [comment]
I'm running a full sweep on Twitter accounts, and will file a PR with updates.
