### ISSUE TITLE
[Data Structure] Add religion=unknown in bio, for missing religion attributes?

### ISSUE THREAD

**Issue by mininternet** [unitedstates/congress-legislators#435]
For structural data consistency, would it be possible to add a **religion : unknown** attribute in the bio section, for those legislators without a known religion? The bio section currently alternates between 2 and 3 attributes due to this column.

Example of a legislator missing this info (there are several): 
"bioguide":"M001170"

_(I understand there are several other issues currently open, so can code for this in my project myself if problematic)_

**Comment by JoshData** [comment]
The field hasn't been maintained since this repo was created in 2012, as far as I can remember, so I would just as well suggest we drop it from our documentation and maybe remove it from the data files.

**Comment by mininternet** [comment]
Ah, i see. I'm performing analytics across the entire data set, so if this field isn't verified, then i suppose i can simply exclude (though is an interesting dimension)

Thanks for all the hard work!
