### ISSUE TITLE
broken photo link

### ISSUE THREAD

**Issue by presentoccupant** [unitedstates/congress-legislators#449]
Pramila Jayapal's photos seem to be missing:
https://theunitedstates.io/images/congress/225x275/J000298.jpg

Image also missing in 450x550.

Effect of broken link can be seen by entering ZIP "98177" at this link:
http://act.commoncause.org/site/PageServer?pagename=sunlight_advocacy_list_page

**Comment by joelcollinsdc** [comment]
Thanks, I believe this is tracked in the images repo.  See https://github.com/unitedstates/images/issues/125

**Comment by presentoccupant** [comment]
Shoot - sorry!
