### ISSUE TITLE
Malformed YAML in legislators-current.yaml

### ISSUE THREAD

**Issue by GoldenJoe** [unitedstates/congress-legislators#450]
The "terms" array is actually just a string with 0 characters. This is because the items that follow are not indented. 

Instead of: 
```
terms:
- arrItem1
  arrItem2
```

It should be:
```
terms:
   - arrItem1
     arrItem2
```

Sorry about formatting, I'm on mobile.

**Comment by GoldenJoe** [comment]
Ugh. The indent doesn't show up. I'll edit when I'm on a PC

**Comment by JoshData** [comment]
That's incorrect. The indentation after a mapping key is optional.

**Comment by GoldenJoe** [comment]
A block style construct is terminated when encountering a line which is less indented than the construct.
Source:
http://www.yaml.org/spec/1.2/spec.html#id2777534

Example:
`$testFile = DATAPATH."legislators/legislators-current.yaml";
$data = Spyc::YAMLLoad($testFile);

echo '<pre>';
print_r($data);
echo '</pre>';`

Output: (truncated after one object for brevity)
`Array
(
    [0] => Array
        (
            [id] => Array
                (
                    [bioguide] => B000944
                    [thomas] => 00136
                    [lis] => S307
                    [govtrack] => 400050
                    [opensecrets] => N00003535
                    [votesmart] => 27018
                    [fec] => 
                    [0] => H2OH13033
                    [1] => S6OH00163
                    [cspan] => 5051
                    [wikipedia] => Sherrod Brown
                    [house_history] => 9996
                    [ballotpedia] => Sherrod Brown
                    [maplight] => 168
                    [icpsr] => 29389
                    [wikidata] => Q381880
                    [google_entity_id] => kg:/m/034s80
                )

            [name] => Array
                (
                    [first] => Sherrod
                    [last] => Brown
                    [official_full] => Sherrod Brown
                )

            [bio] => Array
                (
                    [birthday] => 1952-11-09
                    [gender] => M
                    [religion] => Lutheran
                )

            [terms] => 
            [0] => Array
                (
                    [type] => rep
                    [start] => 1993-01-05
                    [end] => 1995-01-03
                    [state] => OH
                    [district] => 13
                    [party] => Democrat
                )

            [1] => Array
                (
                    [type] => rep
                    [start] => 1995-01-04
                    [end] => 1997-01-03
                    [state] => OH
                    [district] => 13
                    [party] => Democrat
                )

            [2] => Array
                (
                    [type] => rep
                    [start] => 1997-01-07
                    [end] => 1999-01-03
                    [state] => OH
                    [district] => 13
                    [party] => Democrat
                )

            [3] => Array
                (
                    [type] => rep
                    [start] => 1999-01-06
                    [end] => 2001-01-03
                    [state] => OH
                    [district] => 13
                    [party] => Democrat
                )

            [4] => Array
                (
                    [type] => rep
                    [start] => 2001-01-03
                    [end] => 2003-01-03
                    [state] => OH
                    [district] => 13
                    [party] => Democrat
                )

            [5] => Array
                (
                    [type] => rep
                    [start] => 2003-01-07
                    [end] => 2005-01-03
                    [state] => OH
                    [district] => 13
                    [party] => Democrat
                    [url] => http://www.house.gov/sherrodbrown
                )

            [6] => Array
                (
                    [type] => rep
                    [start] => 2005-01-04
                    [end] => 2007-01-03
                    [state] => OH
                    [district] => 13
                    [party] => Democrat
                    [url] => http://www.house.gov/sherrodbrown
                )

            [7] => Array
                (
                    [type] => sen
                    [start] => 2007-01-04
                    [end] => 2013-01-03
                    [state] => OH
                    [class] => 1
                    [party] => Democrat
                    [url] => http://brown.senate.gov/
                    [address] => 713 HART SENATE OFFICE BUILDING WASHINGTON DC 20510
                    [phone] => 202-224-2315
                    [fax] => 202-228-6321
                    [contact_form] => http://www.brown.senate.gov/contact/
                    [office] => 713 Hart Senate Office Building
                )

            [8] => Array
                (
                    [type] => sen
                    [start] => 2013-01-03
                    [end] => 2019-01-03
                    [state] => OH
                    [party] => Democrat
                    [class] => 1
                    [url] => https://www.brown.senate.gov
                    [address] => 713 Hart Senate Office Building Washington DC 20510
                    [phone] => 202-224-2315
                    [fax] => 202-228-6321
                    [contact_form] => http://www.brown.senate.gov/contact/
                    [office] => 713 Hart Senate Office Building
                    [state_rank] => senior
                    [rss_url] => http://www.brown.senate.gov/rss/feeds/?type=all&
                )

        )
`

**Comment by joelcollinsdc** [comment]
This may be an issue that needs to be created in Spyc?

http://pyyaml.org/wiki/PyYAMLDocumentation#Blocksequences

Also validated here:
http://yaml-online-parser.appspot.com/

Not sure if this is a yaml 1.0/1.1/1.2 issue...
