### ISSUE TITLE
icpsr ids

### ISSUE THREAD

**Issue by rshorey** [unitedstates/congress-legislators#452]
yes, I know, everyone's least favorite topic. I've got to do some of these manually for new members for another project, and I'm going to pull them from voteview. Do you want me to dump a full list when I'm done, or is Rachel-munging-voteview-by-hand insufficiently authoritative?

**Comment by JoshData** [comment]
I think you are sufficiently authoritative. :) It'll be helpful to have a deep URL or description of exactly where the IDs came from.

**Comment by rshorey** [comment]
OK, I'll try to think of something concise. For the ones that aren't here (by which I mean aren't in Propublica's API, which pulls from here) I'm name-matching to the voteview DW-nominate download file by hand. I could just link to that document: https://voteview.polisci.ucla.edu/static/data/csv/member/member_both_115.csv
their ID is M{H|S}115XXXXX where XXXXX is the icpsr id.

**Comment by rshorey** [comment]
I don't have time to fix yaml's now and not sure when I'll get to it, but here's my crosswalk for new members if anyone has time first.

F000464,21716
C001112,21709
C001109,21710
C001110,21711
C001111,21712
O000171,21739
P000613,21740
E000297,21715
D000627,21713
K000391,21730
G000579,21720
G000583,21723
H001075,41701
F000465,21717
S001199,21745
T000477,21748
F000466,21718
S001202,41704
S001201,21747
R000607,21742
D000625,21560
D000628,21714
G000580,21721
W000821,21563
B001304,21707
H001074,21725
J000298,21726
R000606,21741
R000609,21744
R000608,21743
H001077,21724
G000581,21722
J000299,21727
K000389,21728
L000586,21732
K000390,21729
L000587,21733
G000578,21719
K000392,21731
T000478,21749
S001200,21746
H001076,41702
C001113,41700
K000393,41703
A000375,21700
B001300,21703
B001302,21705
B001299,21702
B001298,21701
B001301,21704
B001305,21708
B001303,21706
M001199,21735
M001200,21736
M001198,21734
M001201,21737
M001202,21738
