### ISSUE TITLE
Missing Legislators

### ISSUE THREAD

**Issue by GoldenJoe** [unitedstates/congress-legislators#453]
While I was cross-referencing Votes from the unitedstates/congress project with the data in legislators-current, I noticed that information for Xavier Becerra is missing. There may be others. I'll edit if I find more.

**Comment by dwillis** [comment]
Xavier Becerra [resigned](http://bioguide.congress.gov/scripts/biodisplay.pl?index=B000287) Jan. 24, 2017, to become California's attorney general, so he is no longer a current member.
