### ISSUE TITLE
Committee Membership Titles (inconsistency)

### ISSUE THREAD

**Issue by mininternet** [unitedstates/congress-legislators#455]
Is there a particular reason committee titles have multiple values?

Ex:

- Chair
- Chairman
- Vice Chair
- Vice Chairman

There  doesn't seem to be a visible pattern as to when one is used, versus another.  (I also see Cochairman and Co-chairman, though only for 2 records.)

Not sure if this is related to an (understandable) effort to make titles gender-neutral, but just curious as to which are the preferred/established terms.

**Comment by dwillis** [comment]
I don't think there's a particular reason except that individual committees can use their own titles.

**Comment by joelcollinsdc** [comment]
There was some discussion of this in #436 as well

> The House rules were updated a few years back to update chairman and
chairwoman should be changed to chair, etc.

**Comment by mininternet** [comment]
Ok, thanks.

Closing this out then, since i see it being actively discussed in #436.
