### ISSUE TITLE
Update twitter, youtube channels

### ISSUE THREAD

**Issue by pullyl** [unitedstates/congress-legislators#458]
Need to add twitter handles for Higgins, Brown, Taylor
A number of youtube channels that need to be updated

Have made changes locally, but wondering if someone can add me to repo so that I can submit a pr?  Thanks!

**Comment by dwillis** [comment]
Hi @pullyl - if you fork the repository, you should be able to submit a pull request with your changes.

**Comment by pullyl** [comment]
Awesome, thanks @dwillis... clearly still learning how to commit :)

**Comment by pullyl** [comment]
PR merged - https://github.com/unitedstates/congress-legislators/commit/10c978da2f44644f060aafda5b441a030e3ffe4b

Closing issue
