### ISSUE TITLE
Grab Legislators from Specific Congress

### ISSUE THREAD

**Issue by asgeorges** [unitedstates/congress-legislators#461]
The congress-legislators data provided by govtrack does not have the specific congress listed, they only have start/end dates.  I'm wondering if there is a script here that only grabs legislators from a specific congress.

The congress number and start year are linearly dependent, so this can be written into the code.  However, for code readability it would be nice if the congress number can be grabbed in a more natural way from the data.

**Comment by JoshData** [comment]
See [this function](https://github.com/unitedstates/congress-legislators/blob/master/scripts/utils.py#L117) for how to go in the other direction (Congress to dates) accurately. You'd need to invert that function. But also be careful about how Congresses start and end on the same date (at noon).

See #185 for the existing issue on this.

(nb. This repo began with GovTrack's data but is now community maintained.)
