### ISSUE TITLE
incomplete address for Senator Tammy Baldwin

### ISSUE THREAD

**Issue by nijikon** [unitedstates/congress-legislators#471]
There is an incomplete address for Senator Tammy Baldwin, file has `709 Hart` it should be `709 Hart Senate Office Building`.

**Comment by joelcollinsdc** [comment]
This is being pulled from the senate xml like this.  FWIW it also states this on senate.gov.  I notified the webmaster, any opinions on if we should manually fix or just wait?

**Comment by nijikon** [comment]
Are we fixing manually anything right now? Is this the path that we want to take? Cause I have a pile of issues in my notes 😸

**Comment by JoshData** [comment]
Better to get things fixed in the official data than try to play whack-a-mole correcting things here, where possible. For address/contact info, we're not currently making any manual changes.

If you paste all of your notes we can try to route the corrections to the right place.

**Comment by csnardi** [comment]
This seems to be fixed now, the data correctly shows ``709 Hart Senate Office Building`.

**Comment by JoshData** [comment]
Great.
