### ISSUE TITLE
JSON Mirror

### ISSUE THREAD

**Issue by hboylan** [unitedstates/congress-legislators#480]
Many users have requested access to a copy of the data in JSON format. What would it take to implement this?

Someone mentioned using the `gh-pages` branch:
https://github.com/unitedstates/congress-legislators/issues/362#issuecomment-235390150

Issues:
- #362 
- #343

**Comment by JoshData** [comment]
Maybe we can use CircleCI to automatically push alternate formats to `gh-pages` whenever master is updated. That'd maybe allow us to drop the JSON from the master branch, which would make things easier to maintain.

Any other maintainers have a preference?

**Comment by konklone** [comment]
@JoshData I like that idea! And I'd be fine with either Circle or Travis (and we could probably live inside Circle's free tier without too much trouble), if you have a preference. I just moved a couple repos to CircleCI for a work-related project, it wasn't too bad, though it is definitely a more complex/configurable system than Travis.
