### ISSUE TITLE
YAML to JSON conversion doesn't necessarily preserve Twitter ID

### ISSUE THREAD

**Issue by alexlitel** [unitedstates/congress-legislators#503]
Twitter IDs are 64-bit unsigned integers. JavaScript (and by extension JSON) does not support integers beyond 53 bits, so 64-bit Twitter IDs are inevitably coerced and rounded. It's a bit of an unwieldy edge case, but would it be possible to stringify the IDs prior to reserialization?

**Comment by JoshData** [comment]
Good catch, yes we should do that. Submit a PR?

**Comment by alexlitel** [comment]
Fixed in #507,
