### ISSUE TITLE
Data Validation

### ISSUE THREAD

**Issue by mininternet** [unitedstates/congress-legislators#512]
Is there a single source of truth with regards to Congressional metrics? For example, for the 115th Congress, congress.gov lists 547 members, Wikipedia lists 541 members, and legislators-current.yaml lists 540.

Close to releasing a Congressional data visualization dashboard using the data from this repo, but first would like to verify various metrics, though not sure what the best processes and resources for doing so would be. Are there any guidelines, and/or has anyone gone through a similar process with their own project(s)?

For context, here are a few examples of the various metrics being displayed, as well as some of the resources that are being referenced:

 
![ex_state_profile](https://user-images.githubusercontent.com/3261696/30132493-1e6698dc-9316-11e7-8f66-9338df6c863c.png)

![ex_legislator_context_menu](https://user-images.githubusercontent.com/3261696/30133426-72541b10-9319-11e7-9f91-08cc71e5b211.png)

![ex_scatter_plus_chart_types](https://user-images.githubusercontent.com/3261696/30134297-49336e0e-931c-11e7-9a79-025da4010336.png)

![ex_committees_members](https://user-images.githubusercontent.com/3261696/30133531-e0387aa4-9319-11e7-9cdc-d848ca60ed71.png)

Thus far has been a process of constant spot checking, but would be very useful if there were some type of public Congressional reporting utilities to facilitate.

(Apologies if this is not the appropriate place for such an open ended question, just not sure where else to look for discussion related to 'civic hacking' or 'open gov' - haven't found many active communities thus far.)

**Comment by dwillis** [comment]
It depends what you want to display: Congress.gov lists any member who has served during the 115th Congress, while @unitedstates/congress-legislators has a file for _current_ members and one for those who are no longer in congress. Not sure about Wikipedia, but I would not call it a canonical source.

**Comment by mininternet** [comment]
I see, legislators-current.yaml makes sense then, thank you.

As this app is intended for a general audience, Wikipedia is embedded throughout, for both legislator and committee profiles, like so:

![ex_senators_profile](https://user-images.githubusercontent.com/3261696/30150902-d3960fce-9372-11e7-85b9-b22d89ef0fdf.png)

As a layperson, i think Wikipedia (+ social media) can add a valid dimension to the overall profile of public officials, but not sure how that data might conflict with canonical records (nor even entirely sure what qualifies as canonical, aside from congress.gov and govtrack.us).

I'm currently linking to, and using data from: **sunlight foundation**, **propublica**, **ballotpedia**, **countable**, **crowdpac**, **opensecrets**, **us vote foundation**, and **vote smart** (in addition to .gov sites), but not sure what type of discrepancies a casual public user might encounter between them and this repo.
