### ISSUE TITLE
Adding new members without district offices

### ISSUE THREAD

**Issue by bycoffe** [unitedstates/congress-legislators#523]
I'm trying to add John Curtis, R-UT, to the `legislators-current.yaml` file, since he's being sworn in today. He doesn't appear to have any district offices yet. Without an entry (including an office address) in `legislator-district-offices.yaml`, the `validate.py` test fails.

I'm not sure what the best way to handle this is. It seems like we should be able to list new legislators as soon as they're sworn in, even if we don't know the address of a district office. One option might be to include them in the `legislator-district-offices.yaml` file, but without any offices (right now doing that also results in an error). Another might be to make missing offices a warning rather than an error.

Does anyone have thoughts about this? Or is there a way to handle it already and I'm just missing it?

**Comment by JoshData** [comment]
Thanks for getting on this. What about looking at the swearing-in date. We can make it a warning if it's two months (?) after swearing-in without district offices?

**Comment by bycoffe** [comment]
Sounds good to me -- not ideal that whoever makes the first change after two months will see an error even if it's unrelated to their change. But we can encourage whoever adds the member in the first place to keep an eye out for district offices and add when available.

Here's a pull request with that change: https://github.com/unitedstates/congress-legislators/pull/524
