### ISSUE TITLE
Add legislator misconduct data?

### ISSUE THREAD

**Issue by JoshData** [unitedstates/congress-legislators#532]
At GovTrack we're creating a database of legislator misconduct --- anything investigated by Congress's ethics offices or by law enforcement:

https://www.govtrack.us/misconduct

Is there interest in storing that data here? I expect to create a YAML file with records for each investigation and fields holding links to relevant documents and a 'text' key holding a Markdown description of the investigation.

**Comment by JimHarperDC** [comment]
I love legislator misconduct! But to be precise, it appears you're talking about only misconduct that has been the subject of official cognizance or action. That's arguably a small subset of the misconduct legislators do. Be sure to describe it accurately as that limited set of misconduct data.

There is a lot of play in the joints about what is misconduct and what is treated as misconduct. There are false accusations and sometimes false findings and excessive punishments. So the subject matter is a little inconsistent with the bulk of the data here, which is neutral, objective, and not subject to serious debate about the fairness of it, the accuracy with which it depicts events, and so on.

So count this is the mildest of nay votes -- from a  big fan of misconduct!

**Comment by konklone** [comment]
"Big fan of misconduct!" -- Jim Harper

I think it would be useful, as long as it's got some sort of metadata touching on the outcome of investigations, beyond just the full-text description of how the investigation turned out. I think that would speak to Jim's concerns, and make it easier for consumers to filter on the gravity of misconduct or create displays that factor this information in.

**Comment by nerdtypething** [comment]
I think it would be great transparency so long as it is presented as objective and fact-checked.

**Comment by Verser** [comment]
I like it. I agree with the others in the thread. As long as its official misconduct, that has legal investigation, and a node for outcome, it would be great data to have.

**Comment by JoshData** [comment]
Thanks for the feedback all. We're incubating the info at https://github.com/govtrack/misconduct.

**Comment by mattpaz** [comment]
This is great data and seems to be maintained.  Should this issue be closed at this stage?
