### ISSUE TITLE
Reason for end of term

### ISSUE THREAD

**Issue by wilson428** [unitedstates/congress-legislators#571]
Hey folks, been awhile. Is it possible to impute whether a member's term ended when he or she was defeated or chose not to run again?

**Comment by JoshData** [comment]
Hey Chris.

I think if you eliminate the most common end dates for each Congress you'd be left with MoCs that didn't serve out a term. But before 2004ish I don't think we have much data on actual end dates --- they're just coded as going to the end of Congress except when someone did a manual fix, iirc.

**Comment by wilson428** [comment]
Hey bud. I crawled Bioguide and looked for every instance of "was not a candidate for reelection" that wasn't qualified by a run for a different chamber or office. (Lot's of people were not candidates for their House seat because they ran for Senate or Gov or Prez.) So far the results neatly match the "Casualty Lists" that we have going back a few terms.

**Comment by wilson428** [comment]
Thanks for the advice. I'm gonna close this and open an new thread on ideas for bioguide.
