### ISSUE TITLE
Scraping PDF Help

### ISSUE THREAD

**Issue by joepope44** [unitedstates/congress-legislators#578]
Apologies in advance if I am putting this in the wrong place. 

Has anyone experience with scraping government PDFs using python. I am trying to scrape text with PyPDF2 but seem to be unable to decode the text of a specific PDF. This is a publically available document related to data on a member of Congress. 

The documents are encrypted, but I believe I am able to bypass this by using an empty string as the password.  

When I view the PDF 'Contents' I see a dictionary like {'Filter' : 'Flateencode'}.  I believe I need to decode the text data to view, but not sure where to start. Documentation is poor on this.

**Comment by samtregar** [comment]
Link to the PDF?

**Comment by joepope44** [comment]
[hr_test.pdf](https://github.com/unitedstates/congress-legislators/files/2143013/hr_test.pdf)

The file is encrypted, but when I use the .decrypt('') method (passing an empty string as password) and it seems as though that's working.

**Comment by samtregar** [comment]
The file you linked isn't encrypted as far as I can tell.  Is that the real file you're trying to parse?

**Comment by samtregar** [comment]
pdftohtml can handle this file with the -nodrm flag.  The way we do this on the openstates project is to call out to pdftohtml and then load the resulting HTML with lxml.  It's not pretty, but it works.  I'd give that a try if PyPDF2 can't handle this PDF.

**Comment by joepope44** [comment]
Thanks Sam!  I was able to find a utility and get the pdf into html. I suppose I could use lxml or Beautifulsoup (with lxml) from there? 

Can you confirm that you are using this specific tool? http://pdftohtml.sourceforge.net/

There are a few libraries and utilities out there that are variations of pdftohtml.

**Comment by samtregar** [comment]
I'm using the one that comes with Ubuntu, from the poppler-utils package.  I think it's related to that package though, the notes in the manpage also mention xpdf.

**Comment by jsfenfen** [comment]
You might check out pdfplumber, which is handy for more complex / weird pdf extractions https://github.com/jsvine/pdfplumber

**Comment by joepope44** [comment]
pdfplumber was a great option. I was able to parse the text I needed. Thanks!
