### ISSUE TITLE
Congresses served in 

### ISSUE THREAD

**Issue by shmcminn** [unitedstates/congress-legislators#587]
On multiple occasions, I've found myself looking through the `legislatiors-historical` data to find members who served in X Congress. As best I can tell, you have to use the dates of the terms to figure that out, which can be difficult as Congresses don't always start on Jan 3. Could there be an array field with the numbers of Congresses that a legislator served in (ie `[113, 114, 115]`)?

**Comment by JoshData** [comment]
See #185 for an earlier long discussion about this. :)
