### ISSUE TITLE
Troy Balderson

### ISSUE THREAD

**Issue by putorti** [unitedstates/congress-legislators#598]
Seated today: https://twitter.com/jbalmert/status/1037005804602372096

**Comment by JoshData** [comment]
On it....

**Comment by putorti** [comment]
Yeah, I would have included that but I couldn't find it either; curious how do you know what it will be?

**Comment by JoshData** [comment]
It's the next one numerically after the last B-name that's currently assigned.

**Comment by putorti** [comment]
Meanwhile Kyl gets his old one back. 😆

**Comment by JoshData** [comment]
PR at https://github.com/unitedstates/congress-legislators/pull/600. Closing this one.
