### ISSUE TITLE
ICPSR IDs broken

### ISSUE THREAD

**Issue by aaronrudkin** [unitedstates/congress-legislators#601]
Hi. I'm with UCLA Political Science and voteview.com -- we are your provider for ICPSR IDs. I noticed your `icpsr_ids.py` script a) hasn't been updated since the 113th Congress and b) uses out of date URL schemes. When UCLA took over voteview.com after Keith Poole retired from UGeorgia in 2017, we updated the site and thus the URL schemes.

In addition to changing the URLs, we are strongly encouraging people use CSV format files rather than the legacy ORD files we provide. We will be moving to formally deprecate the ORD files in the next year or so and they may be removed in the future.

My guess is you probably want this file for our data:
https://voteview.com/static/data/out/members/HSall_members.csv

If you would prefer individual congress files or individual chambers, the schema is `Cnnn_members.csv`, where `C` is the chamber(s) (H, S, or HS) and `nnn` is a zero-padded integer of length 3 for the number of the congress (i.e. 078 for the 78th congress, 004 for the 4th congress).

So, for the 110th House:
https://voteview.com/static/data/out/members/H110_members.csv

For the 54th Senate:
https://voteview.com/static/data/out/members/S054_members.csv

Relevant fields for mapping to your data:
`bioname`, `bioguide_id`, `chamber`, `icpsr`, `state_icpsr`, `state_abbrev`.

Detailed metadata for the fields provided:
https://voteview.com/articles/data_help_members

Hope this helps. I may have some time to write a PR to replace your script with a current one but in case anyone is actively working on this project I figure I'd open the issue for now.

**Comment by dwillis** [comment]
@aaronrudkin Thanks very much - this is super useful!
