### ISSUE TITLE
Claire McCaskill CSPAN ID

### ISSUE THREAD

**Issue by joeuelk** [unitedstates/congress-legislators#607]
Her CSPAN ID is: 1012014

Used in the URL [https://www.c-span.org/person/?1012014](https://www.c-span.org/person/?1012014), it resolves to this:
[https://www.c-span.org/person/?patbrock02](https://www.c-span.org/person/?patbrock02)

I'm pretty sure the following is the page we want but it uses a name and not a CSPAN ID:
[https://www.c-span.org/person/?clairemckaskill](https://www.c-span.org/person/?clairemckaskill)

**Comment by dwillis** [comment]
@joeuelk thanks - looks like her ID should be 44501, not 1012014.
