### ISSUE TITLE
The 116th Congress

### ISSUE THREAD

**Issue by JoshData** [unitedstates/congress-legislators#615]
Ok. So. We just had an election. See #223 and #375 for how we've handled election results for the past two Congress. Yesterday's special elections are being done in #614.

Yesterday's election was for all representatives (incl. delegates) except Puerto Rico's delegate which is a four-year position and this was an off-year, for a total of 440 seats, and the 33 class 1 senators. The House Clerk promises to provide XML data mid November with bioguide IDs provided for all representatives, so we should use that wherever possible to automate this. I think we'll need to gather Senate results manually.

Cribbing from #375, the overall tasks that need to be done are:

As data comes in:
- [ ] Incumbents that won reelection: Clone their term but update the dates. Check if Senate state junior/senior rank needs to be updated.
- [ ] Legislators that won election to a new seat, e.g. representatives who ran for senate or who changed district number (possibly in PA where the districts were redrawn): Add a term with new information. Senate terms are likely junior rank.
- [ ] Incumbents and legislators who ran for a different seat but lost: Run the `retire` and `sweep` scripts to move them to the legislators-historical file and clear their committee and social media records.
- [ ] Winners who served in Congress previously: Move their record from the legislators-historical file to the legislators-current file and check if any missing metadata can be filled in. Senators are likely junior rank.
- [ ] Winners who are new: Add per the [new member template](https://github.com/unitedstates/congress-legislators/blob/master/misc/new-member-template.yaml). Senators are likely junior rank. We should have all representative bioguide IDs soon but senator bioguide IDs may not be available until they are sworn in.
- [ ] Add end dates to all current `leadership_roles` for Members who are no longer serving.
- [ ] Committee assignments must be cleared.
- [ ] [Photos](https://github.com/unitedstates/images) need to be found for new members.
- [ ] Social media accounts can be added for new members.

After January 3:
- [ ] Fix start dates to actual swearing in dates if any legislators didn't get sworn in on the first day.
- [ ] Bioguide IDs must be filled in when they become available. We have a script to guess IDs. We should know all representative IDs by now but not Senate IDs.
- [ ] New leadership roles
- [ ] Fill in the inevitable missing data, like office addresses (via the `house_contacts.py` and `senate_contacts.py` scripts) and committee membership.

**Comment by JoshData** [comment]
The House clerk has posted unofficial data on the 116th Congress membership:

http://clerk.house.gov/member_info/unofficial-116-member-elect-data.xml

I am going to start a branch for the 116th Congress this weekend.

**Comment by frisch1** [comment]
Hi Josh...

Y'all have been a big help. Not sure what format would be best, but please see the attached, as follows:

- New members only for 116th (House/Senate)
- Includes Harris NC09, just in case
- uses the Dec. 13th House XML, plus known Senator-elects, as keys.
- Adds
-- bioguide IDs where known (source: house clerk, previous IDs for Senators where avail)
-- All known social media: twitter, facebook, instagram, youtube. Labels as campaign, official, personal or other
-- Adds opensecrets_id, votesmart_id, fec_ids, cspan_ids, wikipedia_ids, ballotpedia IDs

We have most of the photos, but we use this for machine learning vs public, so don't know clearances for reuse, though nearly all are either CC wiki, or from campaign.

Hope this data is useful. If a better format, LMK what would work. Just CSV
[116th.xlsx](https://github.com/unitedstates/congress-legislators/files/2711531/116th.xlsx)

**Comment by mikeshyavitzcbo** [comment]
Happy New Year and Happy New Congress! Just ran a pull request on the 116th congress and got 0 members. I realize it hasn't started yet, but any idea when we might see data start filling up there? Thanks for all the great work on this.

**Comment by JoshData** [comment]
I've been working on this in #625, which barring any unexpected issues I will merge at noon tomorrow, which is when the 116th Congress begins.

**Comment by mikeshyavitzcbo** [comment]
Awesome. Thank you!

**Comment by dwillis** [comment]
I can add FEC IDs to the House freshmen class, if no one else is working on it. cc @JoshData
