### ISSUE TITLE
116th Congress Committee Data

### ISSUE THREAD

**Issue by mikeshyavitzcbo** [unitedstates/congress-legislators#630]
Just want to track progress on getting the 116th committee memberships updated. Right now it looks like the majority of them are blank. Any idea on a roadmap? Or a way to help contribute data?

**Comment by dwillis** [comment]
Most committee assignments haven't been officially announced yet.

**Comment by mikeshyavitzcbo** [comment]
Looks like it's already filling up. Thanks!

**Comment by composerinteralia** [comment]
Am I correct that we are scraping this committee information from pages like http://clerk.house.gov/committee_info/index.aspx?comcode=BA00 ? Do we have any insight into when the new committee memberships will be available?

**Comment by dwillis** [comment]
Memberships are still being announced by House leaders, and I'd expect they'd be completely done within a few weeks. Most committees haven't had organizational meetings yet.

**Comment by michaelblyons** [comment]
Majority/Minority website urls are out of date.

**Comment by dwillis** [comment]
A question: would people be interested in adding start dates to committee assignments and/or url of the resolution naming the assignments? I realize this would add an additional maintenance burden.

**Comment by mikeshyavitzcbo** [comment]
I know some committees have started to announce memberships (e.g. https://budget.house.gov/news/press-releases/chairman-yarmuth-announces-house-budget-committee-democratic-members), but the house clerk's site is still not updated as mentioned above. Is that the official data source? I sent them an email too and will post here what they say if I hear back.

**Comment by dwillis** [comment]
I've always treated the sources in this order of officialness:

1. Actual house or senate resolution appointing members
2. Leadership press release
3. Committee website
4. Member press release

**Comment by konklone** [comment]
I'm curious, have you ever seen discrepancies between any of those 4?

**Comment by dwillis** [comment]
Only in terms of timing - sometimes members will announce that they have been named to a committee before it actually happens.

**Comment by dwillis** [comment]
Any objection to us ditching the `thomas` id for current committee membership file? We've got bioguide in there and I'm not sure there's a good use case for thomas.

**Comment by dwillis** [comment]
Thanks, @JoshData. I'm working through the House assignments, about half-way there. A bunch of subcommittee assignments were published today, too.

**Comment by mikeshyavitzcbo** [comment]
Hi All - House Budget Committee assignments are up, but still no update in the data source. Any idea on this? 

source: http://clerk.house.gov/committee_info/index.aspx?comcode=BU00

**Comment by dwillis** [comment]
@mikeshyavitzcbo As I said before, I'm working on it - hoping to do the entire House and Senate at once, including subcommittees. Goal is to finish this week.

**Comment by dwillis** [comment]
Just an FYI, I am hoping to have a pull request with all 116th committee and most subcommittee assignments on Feb. 7.

**Comment by mikeshyavitzcbo** [comment]
It's looking pretty good so far. I noticed the House Budget Committee only has about 20 members in the data source, but their web site is showing more: https://budget.house.gov/about/membership 

Is there anything we can do to report inconsistencies? Or is the data just catching up do you think? 

Thanks,
Mike

**Comment by dwillis** [comment]
@mikeshyavitzcbo I think you just reported one :-)

**Comment by dwillis** [comment]
House Budget committee GOP membership has been completed.

**Comment by mikeshyavitzcbo** [comment]
Thank you!

**Comment by dwillis** [comment]
I will periodically be updating committee membership throughout the congress, so am proposing we close this issue.

**Comment by mikeshyavitzcbo** [comment]
Thanks for all your help on this!
