### ISSUE TITLE
Missing Jared Golden (ME-02) for 116th

### ISSUE THREAD

**Issue by doshitan** [unitedstates/congress-legislators#632]
The election was challenged and the lawsuit only dropped at the end of December, so maybe things are weird.

**Comment by frisch1** [comment]
Still can't find a bioguide for him, but his info is up finally on the clerk site:
http://clerk.house.gov/member_info/mem_contact_info.aspx?statdis=ME02
Maine-2nd, Democrat
1223 Longworth HOB 
Washington, DC 20515-1902
Phone: (202) 225-6306
https://golden.house.gov/
