### ISSUE TITLE
Walter Jones (116th Congress)

### ISSUE THREAD

**Issue by bycoffe** [unitedstates/congress-legislators#638]
Rep. Walter Jones (R-N.C.) was not sworn in with the other members on 2019-01-03 because of a medical issue, so he's not appearing in roll calls yet. (http://www.dailyadvance.com/News/2019/01/04/div-Jones-misses-oath-in-D-C-div.html)

Once he's sworn in, should his term start date be changed in `legislators-current.yaml`? I'm not sure how such situations have been handled in the past.

**Comment by dwillis** [comment]
I think his start date should be changed to his swearing-in date. That's how we plan to handle it in the ProPublica API, fwiw.

**Comment by JoshData** [comment]
+1

**Comment by bycoffe** [comment]
Pull request: https://github.com/unitedstates/congress-legislators/pull/647
