### ISSUE TITLE
Religion data is very incomplete

### ISSUE THREAD

**Issue by YairRand** [unitedstates/congress-legislators#657]
The religion field is very incomplete. Pew has lists of religions of members of the 111th-116th congresses, mostly (entirely?) compiled from CQ Roll Call surveys:
* 111th: http://assets.pewresearch.org/wp-content/uploads/sites/11/2008/12/appendix.pdf
* 112th: http://assets.pewresearch.org/wp-content/uploads/sites/11/2011/01/relig-affil-pdf-updated-2-24-111.pdf
* 113th: http://assets.pewresearch.org/wp-content/uploads/sites/11/2012/11/113-congress-relig-affil.pdf
* 114th: http://www.pewforum.org/2015/01/05/members-of-congress-religious-affiliations/
* 115th: http://assets.pewresearch.org/wp-content/uploads/sites/11/2017/01/19161723/Member-affiliations-for-web.pdf
* 116th: http://www.pewforum.org/wp-content/uploads/sites/7/2019/01/Detailed-tables-NUMBER-CHECK-COMPLETE-1-3.pdf

Could this data be added?

**Comment by JoshData** [comment]
I'm not sure if this would be right to add without permission from Pew and CQ.

**Comment by dwillis** [comment]
I agree with Josh on this. Personally, I don't think it's something that we should be tracking with this repo, but I can understand the interest and potential research value.

**Comment by JoshData** [comment]
If there's no objection, I will open a PR that deletes all of the religion data we have so there's no confusion.

**Comment by dwillis** [comment]
No objection here.

**Comment by JoshData** [comment]
Per our fairly limited consensus, we're not going to include religion data in this dataset at this time, so I'm going to close the issue. I'm sure we'd be glad to continue talking about a strategy to consolidate the data.
