### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by mikeshyavitzcbo** [unitedstates/congress-legislators#664]
Hi All - Just noticed today I'm getting 500 internal server errors when making just about any call to the API. Any idea what's up? Is it just me?

**Comment by dwillis** [comment]
@mikeshyavitzcbo I'm guessing you mean the ProPublica API? If so, it's not just you. We're on it.

**Comment by mikeshyavitzcbo** [comment]
Awesome - thanks
