### ISSUE TITLE
Michael Bennet's Congressional Statements

### ISSUE THREAD

**Issue by poastertoaster** [unitedstates/congress-legislators#669]
Most senators have an RSS feed on their senate website that is used to pull congressional statements, from what I can tell. Michael Bennet does not have congressional statements being pulled, but he does have a feed on his website of statements.

https://www.bennet.senate.gov/public/index.cfm/press-releases

I am uncertain if it is in a format that is not able to be pulled easily, but it is available so I thought I'd make this issue known.

**Comment by dwillis** [comment]
@poastertoaster Hi, and thanks. I don't know that I agree that most senators have RSS feeds on their websites. At ProPublica I pull in House & Senate statements and we have to scrape nearly all Senate sites as most have dropped their RSS feeds. Happy to be proven wrong, though, so if you find RSS feeds please post the links!
