### ISSUE TITLE
caucus: ~  is invalid when party is Independent.

### ISSUE THREAD

**Issue by jeremydouglass** [unitedstates/congress-legislators#689]
From circleci:

> legislators-current.yaml:A000367:terms[4](2019-01-03 to 2021-01-03): caucus: ~
 is invalid when party is Independent."

This refers to Justin Amash, who is indeed Independent and I believe did withdraw from the House Republican Conference. Maybe change the validation rule? Or add "caucus: None"? It is unusual, but there isn't actually some rule that Independents must caucus with somebody....

**Comment by JoshData** [comment]
Right. The check can be removed and the README should be updated to reflect that caucus can be null.
