### ISSUE TITLE
Historical: Terms should end on January 3rd

### ISSUE THREAD

**Issue by konklone** [unitedstates/congress-legislators#7]
Instead of December 31st. Terms both start and end on that day, since it ticks over at noon.

**Comment by konklone** [comment]
A note for anyone still subscribed to this thread, technically or emotionally, that @JoshData has filed a fix for review at #305.

**Comment by JimHarperDC** [comment]
I am emotionally subscribed to this thread, but not technically. ('Scuse the interruption... Had to.)

**Comment by JoshData** [comment]
This was fixed by the above commit (428d714).
