### ISSUE TITLE
CSV links for legislators go nowhere

### ISSUE THREAD

**Issue by SeijiSensei** [unitedstates/congress-legislators#712]
These links do not seem to work:

https://theunitedstates.io/congress-legislators/legislators-current.csv
https://theunitedstates.io/congress-legislators/legislators-historical.csv

Opening them brings up a blank page.

**Comment by dwillis** [comment]
@SeijiSensei was just able to download both - how are you accessing them?

**Comment by SeijiSensei** [comment]
Must have been an issue with browser settings.  I successfully retrieved both files with a different browser (Brave) on a different machine.

Thanks for the quick reply!

Dr. Peter H. Lemieux
