### ISSUE TITLE
Missing type field for select terms in historic legislators files (yaml)

### ISSUE THREAD

**Issue by ekamptner** [unitedstates/congress-legislators#731]
Hi, 

Some term types were missing for select terms in the historic legislators files. Specifically --

* 'rep' missing from 18th term representatives
* 'sen' missing from 6th term senators

**Comment by JoshData** [comment]
Could you point to a particular example or give a line number (and which file are you looking at --- yaml, csv, json)?

**Comment by ekamptner** [comment]
Apologies! Please disregard. I believe I found the issue on my end when importing data.
