### ISSUE TITLE
Ted Cruz  / Rafael Edward (Ted) Cruz 

### ISSUE THREAD

**Issue by imjonathan** [unitedstates/congress-legislators#750]
I'm not clear on what data is considered authoritative, but I was confused that nowhere in the Ted Cruz record ( bioguide: C001098 ) does his full legal name: Rafael Edward Cruz  appear.

**Comment by dwillis** [comment]
@imjonathan this isn't an official government project, and our policy is to use the name that the member chooses to use publicly.

**Comment by imjonathan** [comment]
Perhaps it would be useful to add a legal name col? 
Perhaps from: 
url = https://bioguide.congress.gov/search/bio/{{bioguide}}
xpath='/html/body/div[1]/div/div[2]/div/div[1]/div[1]/div[4]/div/h1'

**Comment by dwillis** [comment]
Since that information is easily retrievable from the Bioguide site as JSON or XML (https://bioguide.congress.gov/search/bio/C001098.json, for example), I'm not sure why we'd need to include here.

**Comment by imjonathan** [comment]
@dwillis Now I know. Thank you!
