### ISSUE TITLE
Pelosi leadership role update

### ISSUE THREAD

**Issue by svallen** [unitedstates/congress-legislators#758]
Legistlative -> Current JSON

Nancy Pelosi needs her leadership role updated with the current speaker of the house time frame.

**Comment by JoshData** [comment]
Hi @svallen. I moved this issue to the correct repository.

I'm also embarrassed I left out the most important leadership role when I did the other updates! I'll fix this later today. Thank you.

**Comment by JoshData** [comment]
Fixed, thanks!

**Comment by svallen** [comment]
Awesome. Thanks!
