### ISSUE TITLE
committee-membership-current is empty

### ISSUE THREAD

**Issue by imjonathan** [unitedstates/congress-legislators#759]
So I wanted the committee-membership-current.yaml, but it is empty.

I tried running: scripts/committee_membership.py to see if I could generate it,

But the GA special election has me stumped...

`Traceback (most recent call last):
  File "committee_membership.py", line 349, in <module>
    run()
  File "committee_membership.py", line 42, in run
    raise ValueError("Member's last listed term is not current: " + repr(moc) + " / " + term["start"])
ValueError: Member's last listed term is not current: {'id': {'bioguide': 'L000594', 'lis': 'S405', 'fec': ['S0GA00526'], 'govtrack': 456790, 'wikipedia': 'Kelly Loeffler', 'wikidata': 'Q76570207', 'ballotpedia': 'Kelly Loeffler', 'opensecrets': 'N00046125', 'google_entity_id': 'kg:/g/11j3kgpjlx', 'votesmart': 188718}, 'name': {'first': 'Kelly', 'last': 'Loeffler', 'official_full': 'Kelly Loeffler'}, 'bio': {'gender': 'F', 'birthday': '1970-11-27'}, 'terms': [{'type': 'sen', 'start': '2020-01-06', 'end': '2021-01-15', 'how': 'appointment', 'end-type': 'special-election', 'state': 'GA', 'class': 3, 'party': 'Republican', 'state_rank': 'junior', 'url': 'https://www.loeffler.senate.gov', 'address': '131 Russell Senate Office Building Washington DC 20510', 'office': '131 Russell Senate Office Building', 'phone': '202-224-3643', 'contact_form': 'https://www.loeffler.senate.gov/connect/email-kelly'}]} / 2020-01-06`

**Comment by JoshData** [comment]
You're running a little bit behind --- I committed the special election results earlier this week. After getting those changes, it should work fine. I actually just ran it and committed/pushed the results.

**Comment by imjonathan** [comment]
Hmmm.... I show I am up to date

% git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

**Comment by JoshData** [comment]
You probably need to run `git fetch` or `git pull`.

**Comment by imjonathan** [comment]
You rule! Thank you.
