### ISSUE TITLE
Nickname for Joe Biden

### ISSUE THREAD

**Issue by pauly815** [unitedstates/congress-legislators#774]
In the executives data could a nickname of "Joe" be added for current president Joe Biden?

**Comment by JoshData** [comment]
I'd be OK with that. Will wait for feedback from others.

**Comment by mattpaz** [comment]
It looks this was added at some point.
https://github.com/unitedstates/congress-legislators/blob/main/executive.yaml#L1508
I'm guessing this could probably be closed?
