### ISSUE TITLE
Rick Scott Missing 8 District Offices

### ISSUE THREAD

**Issue by putorti** [unitedstates/congress-legislators#792]
For Rick Scott (S001217) only the Tallahassee office is listed but he has [8 more offices listed here](https://www.rickscott.senate.gov). I didn't look to see if there are other Senators with only a single district office, but if so, probably a bug.

801 North Florida Avenue
Suite 421,
Tampa FL  33602
Phone: (813) 225-7040

3299 Tamiami Trail East
Building F, #106
Naples, FL 34112
Phone: (239) 231-7890

225 East Robinson Street
Suite 410,
Orlando, FL 32801
Phone: (407) 872-7161

415 Clematis Street
Suite 201,
West Palm Beach FL  33401
Phone: (561) 514-0189

901 Ponce de Leon Boulevard
Suite 505
Miami, FL 33134
Phone: (786) 501-7141

221 Palafox Place
Suite 420,
Pensacola, FL 32502
Phone: (850) 760-5151

1 Courthouse Square
Suite 300
Kissimmee, FL 34741
Phone: (407) 586-7879

400 West Bay Street
Suite 289,
Jacksonville, FL 32202
Phone: (904) 479-7227

**Comment by jlev** [comment]
Hey Jason, I'm not sure if the district offices are kept up to date by scrapers. I know the original work to bring them all in was manual, and mainly done by @arrighik at ControlShift. Might be worth another community push to get that up to date, since we're all relying on the same data source.

**Comment by jlev** [comment]
💯
