### ISSUE TITLE
A handful of zip codes in the district addresses dataset are not parsed as strings

### ISSUE THREAD

**Issue by rolandcrosby-check** [unitedstates/congress-legislators#799]
All nine-digit zip codes in legislators-district-offices.yaml are parsed as YAML strings (because they have non-numerical characters in them), and most five-digit zip codes are quoted (which makes them parse as strings), but [these particular offices' zip codes](https://github.com/unitedstates/congress-legislators/blob/fcabd4c/legislators-district-offices.yaml#L11361-L11430) are not quoted and parse as numbers.

**Comment by GPHemsley** [comment]
Looks like these all originated from fcabd4c9e152885a1d6f242e0a3c878ce3d4cbab (#794).

**Comment by jlev** [comment]
Sorry for that, folks.
