### ISSUE TITLE
Incorrect FEC identifier for Kevin McCarthy

### ISSUE THREAD

**Issue by poliquin** [unitedstates/congress-legislators#801]
The `legislators_current.yaml` file contains an incorrect FEC identifier for Kevin McCarthy.

There are two identifiers in the file: `H6CA22125` and `H2CA23148`. Only `H6CA22125` is valid. The second identifier actually belongs to [Bruno Amato](https://www.fec.gov/data/candidate/H2CA23148/), who is challenging McCarthy for his seat.

**Comment by JoshData** [comment]
Thanks. I was just about to make another correction. Fixing in #802.
