### ISSUE TITLE
Project Seldon

### ISSUE THREAD

**Issue by skipjack** [unitedstates/congress-legislators#803]
We just wanted to stop by to thank everyone who's contributed this repo! We're building a web app called Project Seldon with the goal of being _an unopinionated analysis platform for understanding societies and systems of government_. We leverage the data here as the baseline for our interactive US seating charts and detail pages (shown in the following video). We've scraped some similar data for other countries though unfortunately few others have sources that are quite as comprehensive.

https://user-images.githubusercontent.com/8988697/149716478-f05ca709-1ed4-4500-9d7e-7a65c21ad275.mp4

In any case, we wanted to offer you all access to the site (currently in private beta as we flesh out bugs and ensure everything is fairly accurate and transparently sourced). It's whitelisted by email so just drop us (@skipjack or @gerard070) a line here or reach out to me at greg.venech@gmail.com if you'd like access. We're still debating whether to go the non-profit or for-profit route (leaning towards the former) but either way...

- We'll be publishing all the functionality you see in the video + more for free in the late spring or early summer.
- We'll be open-sourcing certain aspects of site (e.g. the data collection / scraper scripts).
- We've already linked to this repo anywhere the data here is used.
- We're happy to have those links point to wherever you'd like.
- We'd consider introducing functionality that lowers the barrier to entry for contributing to repos like this one.

Regarding the last bullet, think something like the user filling out a form, or uploading a spreadsheet with all the data points and sourcing required. We'd hope that something like that might make it easier to create repos like this one for other countries. Thoughts on that and any other feedback/ideas would be much appreciated!

Also, please let me know if this issue is the proper forum... happy to move it over to a GitHub discussion or something else if you'd prefer.

**Comment by skipjack** [comment]
@JoshData based on the [contribution activity][1] and the responses I'm seeing on issues, you seem to be the most active maintainer. Would love to get your thoughts on the project if you have some time to check it out.

[1]: https://github.com/unitedstates/congress-legislators/graphs/contributors

**Comment by JoshData** [comment]
Hi. Thanks. I'm sorry I don't have time to provide feedback to new projects.

**Comment by skipjack** [comment]
No worries, do you mind if I leave the issue open for a bit? I'm looking to start discussing the project with technical journalists interested in exactly the kind of data offered here.

Also, are you looking for any help maintaining this repo? We'd be happy to help contribute and review issues/prs.
