### ISSUE TITLE
Missing congress people twitter handle on legislator-social-media.json

### ISSUE THREAD

**Issue by fre5** [unitedstates/congress-legislators#805]
Name : Rep. Andrew Clyde
Twitter handle: @Rep_Clyde

**Comment by fre5** [comment]
Name: Rep. Shontel Brown
Twitter handle: @ShontelMBrown

**Comment by dwillis** [comment]
@fre5 thanks, but that's her campaign account, not her official one, so it doesn't get included here.

**Comment by fre5** [comment]
> @fre5 thanks, but that's her campaign account, not her official one, so it doesn't get included here.
thanks @dwillis, I fixed it.

**Comment by JoshData** [comment]
Thanks! Merged in #809.
