### ISSUE TITLE
When was the last update done on the Congress List? Is this correct?

### ISSUE THREAD

**Issue by ArmancaM** [unitedstates/congress-legislators#810]
https://docs.google.com/spreadsheets/d/1tCW1uHhWhfVtZO8Vkflg9GnvQf_eqH2F--HAriZYFqI/edit#gid=1178631925

**Comment by dwillis** [comment]
@ArmancaM I'm sorry, but we're not able to check your work, but the list of current legislators in this repository is up to date.

**Comment by ArmancaM** [comment]
Thank you so much! You are so kind for responding.
