### ISSUE TITLE
Missing opensecrets id for several legislators in legislators-current.yaml

### ISSUE THREAD

**Issue by admarwick** [unitedstates/congress-legislators#849]
I'll submit a PR with the missing data shortly.

The records to be modified are for:
Shontel M. Brown
Mike Carey
Sheila Cherfilus-McCormick
Connie Conway
Mayra Flores
Mike Flood
Brad Finstad
Mary Sattler Peltola
Patrick Ryan
Joseph Sempolinski

**Comment by mattpaz** [comment]
I think this issue could probably be closed, eh?
