### ISSUE TITLE
Birthdays Missing

### ISSUE THREAD

**Issue by lindseycormack** [unitedstates/congress-legislators#867]
It seems like a one or more birthdays are missing (found out when a script of mine for DCinbox relies on these).

I don't know how to directly edit the legislators-current.yaml (and it's possible I can't), but I called the individual representatives offices today and here are the reported birthdays:

Budzinski, Nikki B001315 1977-3-11
Lee, Laurel L000597 1976-3-26
Ezell, Walter (Mike) E000235 1959-4-6
Williams, Brandon W000828 1967-5-22
Salinas, Andrea S001226 1969-12-6

Still waiting for details on the following (sent emails after calling, waiting for responses):
Pettersen, Brittany P000620 1981-12-
Moylan, James M001219
Deluzio, Christopher D000530

**Comment by dwillis** [comment]
@lindseycormack thanks! had no idea you were using this data for DC Inbox, but that's very cool. Editing the yaml file is like editing a text file, but I'm happy to make these changes.

**Comment by dwillis** [comment]
@lindseycormack one thing: the congressional biographical directory says that Laurel Lee was born in 1974, not 1976 (but does not provide a month or day).

**Comment by lindseycormack** [comment]
Hi - yes, that detail is correct, I just called again. It's 1974-3-26.

**Comment by dwillis** [comment]
@lindseycormack thanks!
