### ISSUE TITLE
Sen. Pete Rickets -- Missing

### ISSUE THREAD

**Issue by swt83** [unitedstates/congress-legislators#872]
https://en.wikipedia.org/wiki/Pete_Ricketts

Took the seat on Jan 23, 2023.

EDIT: I see somebody is on the case:
https://github.com/unitedstates/congress-legislators/pull/871

**Comment by JoshData** [comment]
Sorry I'm usually on top of this but haven't been able to make time yet. Hopefully this weekend (if no one completes it first).
