### ISSUE TITLE
The 118th Congress - leadership_roles

### ISSUE THREAD

**Issue by mattpaz** [unitedstates/congress-legislators#877]
Is population of `leadership_roles` in `legislators-current.yaml` for the 118th Congress pending?
Possibly related to: https://github.com/unitedstates/congress-legislators/issues/827

**Comment by JoshData** [comment]
It's not something I'm working on (due to lack of time) but I'd gladly merge a PR with it. 

If someone wants to do it please follow the pattern in https://github.com/unitedstates/congress-legislators/pull/660.

**Comment by mattpaz** [comment]
Thanks for the update and for citing prior work.  One quick question.  Is the data manually curated or harvested via python scraping?  Based on [this commit](https://github.com/unitedstates/congress-legislators/pull/660/commits/e8af774a9f151a399b460aaf74e9a6394e3e5947), it looks like it might involve manually updating the yaml using the conventions cited in that PR.  If so, I could probably send a PR over. 

I'm guessing [this commit](https://github.com/unitedstates/congress-legislators/pull/660/commits/dc6fde4ed65f88edf11568d0522eca17b439f447) is separate from the actual data updates?

**Comment by JoshData** [comment]
> manually updating the yaml

That's right. As I recall, I did it manually in a text editor.

> [this commit](https://github.com/unitedstates/congress-legislators/pull/660/commits/dc6fde4ed65f88edf11568d0522eca17b439f447) is separate from the actual data updates?

Yeah I don't think that was related. I probably just noticed around the same time as working on other things.
