### ISSUE TITLE
Missing Committee Members

### ISSUE THREAD

**Issue by mattpaz** [unitedstates/congress-legislators#886]
There seem to be many subcommittees (like `HSSY20`) that don't include the members.  
If these are manually curated, I'd image a PR would be welcome?

https://github.com/unitedstates/congress-legislators/blob/main/committee-membership-current.yaml#L4476

**Comment by JoshData** [comment]
It's updated by https://github.com/unitedstates/congress-legislators/blob/main/scripts/committee_membership.py from XML data from the House and Senate. We run the script manually periodically. I just ran it and pushed the update.

**Comment by mattpaz** [comment]
Ah, cool. I didn't realize that xml data existed.  Thanks for pointing me in the direction of the python code and for running an interim update too.

The updates definitely filled in some gaps!

I'll take a deeper look at the python script and upstream sources at some point.
In the meantime, I'll just cite some of those that still have no committee members listed.

```
HLIG03
HLIG05
HLIG08
HLIG10
HSBA13
HSBA15
HSED07
HSGO02
HSGO25
HSGO28
HSGO29
HSHA01
HSII22
HSRU05
HSSM25
HSSM26
SSCM26
SSCM27
SSCM28
SSCM29
SSCM30
SSCM31
SSCM32
SSEV16
SSEV18
SSFR12
SSFR13
SSGA15
SSGA16
SSGA17
SSGA18
SSGA19
```

Looking at the `committees_current` source, it seems that maybe it simply needs to be reviewed/updated before re-running the script?

I wonder if we could use this: 
https://api.congress.gov/#/committee/committee_list
as a good source for updates?

I'll try to compare the data in the congress.gov apis to the data in committee_current at some point (if someone doesn't beat me to it.

---

Thanks again!

**Comment by JoshData** [comment]
It's also possible the subcommittee has no members or that it exists only on paper. But defunct might be the most likely.

**Comment by mattpaz** [comment]
I've completed a review of the defunct committees and have a PR started here:
https://github.com/unitedstates/congress-legislators/pull/890

Take a look and let me know if I missed anything.

**Comment by mattpaz** [comment]
With https://github.com/unitedstates/congress-legislators/pull/890 committed, I think we can probably close this issue.
