### ISSUE TITLE
Franklin C. Scott Name Mistake

### ISSUE THREAD

**Issue by c-jimmy1** [unitedstates/congress-legislators#893]
It seems like Franklin's name in the csv file is flipped. It has `C.` as the first name, and `Scott` as the middle name. `C.` is supposed to be the middle name. Thanks!

**Comment by JoshData** [comment]
Based on a few minutes of research it appears to be correct, so I am closing this.

**Comment by c-jimmy1** [comment]
I apologize, most websites said Scott Franklin but the congress website says C. Scott Franklin, you're right, thanks!
