### ISSUE TITLE
Rep. Brian Higgins Resigned

### ISSUE THREAD

**Issue by prdurkin23** [unitedstates/congress-legislators#916]
I believe Rep. Brian Higgins is still listed as active for NY-22. He [resigned](https://www.politico.com/live-updates/2024/02/01/congress/higgins-resign-house-new-york-democrats-00139047) from Congress last month.

<img width="843" alt="image" src="https://github.com/unitedstates/congress-legislators/assets/121575069/44458bff-2ea0-4f24-9a66-7e2e767dd4d5">

**Comment by JoshData** [comment]
Thanks. Found out there was another resignation in January that we missed. PR in #917.

**Comment by prdurkin23** [comment]
Thanks for the quick update, @JoshData and @dwillis! 😄
