### ISSUE TITLE
Incorrect information for Govtrack IDs 412464 and 456856

### ISSUE THREAD

**Issue by SacriliciousQ** [unitedstates/congress-legislators#920]
In the YAML file for legislators-current, ID 412464 (Senator James Lankford) is flagged as a Junior Seat, but Lankford is actually the Senior Seat.  The same is true for ID 456856 (Senator Alejandro Padilla).

**Comment by JoshData** [comment]
Hi.

In the last (most recent) term entry listed for both senators, they have `state_rank: senior`. So I think the data is correct. You might be looking at the wrong term entry?

It is possible that these fields go out of date especially after a resignation of the other senator, so it's great to keep a careful eye on whether it's correct, but I think in these cases they look correct.

**Comment by SacriliciousQ** [comment]
It doesn't show as senior for me.

This is the link I'm looking at:  https://theunitedstates.io/congress-legislators/legislators-current.yaml

Check it out for govetrack 412464.  I'm including a screenshot to show it saying "junior" for me.

![GovtrackScreenshot](https://github.com/unitedstates/congress-legislators/assets/52014332/416a58e8-aa72-4938-9b05-d5f5cae5f433)

**Comment by SacriliciousQ** [comment]
Ah, I see what's going on now.  There are more state_ranks for those people than I thought.  So I have to go farther down in their record to fish out the correct one.

Thanks!

**Comment by JoshData** [comment]
No problem. :)
