### ISSUE TITLE
New Member: Rep. Tim Kennedy (D-NY)

### ISSUE THREAD

**Issue by prdurkin23** [unitedstates/congress-legislators#924]
[Tim Kennedy won a special election](https://www.politico.com/news/2024/04/30/tim-kennedy-wins-special-election-00155271) to replace former Rep. Brian Higgins. He will be sworn into Congress shortly. Can we please add him?

**Comment by dwillis** [comment]
@prdurkin23 when he gets sworn in we will; that could be anytime within the next two weeks, after the election has been certified.
