### ISSUE TITLE
Sen. Joe Manchin Party Change

### ISSUE THREAD

**Issue by prdurkin23** [unitedstates/congress-legislators#927]
Sen. Manchin [announced](https://www.manchin.senate.gov/newsroom/press-releases/manchin-registers-as-independent) he has left the Democratic Party and is now an Independent. Can we please update his party for his current term?

**Comment by dwillis** [comment]
@prdurkin23 this is done now in 4b391a4fa5078686b0a5fed71bf3fc750ba59a53
