### ISSUE TITLE
[Question] About Politicians with Multiple Bioguide ID

### ISSUE THREAD

**Issue by haiss3088** [unitedstates/congress-legislators#938]
Hi,

Thank you for your efforts in constructing and maintaining this dataset. I really appreciate it!

I was wondering if it is possible to identify which politicians have multiple Bioguide IDs. Is it possible to get this list using the current features of the dataset?

Thank you for addressing my concerns.

**Comment by dwillis** [comment]
@haiss3088 afaik, there should be no legislators with multiple Bioguide IDs. A handful of folks did previously - usually involving lawmakers who changed their surnames - but those have been resolved, to my knowledge.

**Comment by haiss3088** [comment]
Ah I see, thank you so much for answering my question!
