### ISSUE TITLE
Would this project accept PR with ids for GPO's Pictorial API

### ISSUE THREAD

**Issue by kevinschaul** [unitedstates/congress-legislators#942]
I am working on updating a script in unitedstates/images, and it involves matching legislators with their [GPO Pictorial API ids](https://pictorialapi.gpo.gov/api/GuideMember/GetMembers/118). (Unfortunately that API does not include Bioguide IDs.) There are some tricky cases, and so I think the join will require a manual lookup for some legislators with common names. That makes me think the lookup might work well in this repo instead.

Would this repo accept a PR with these ids, and a script to help generate them automatically?

My WIP script is [here](https://github.com/kevinschaul/us-images/blob/f42451ae5baf3159d393ed7b954169120bc33fb9/scripts/gpo_member_photos.py#L77). Happy to transfer it to this repo if you all think that makes sense.

**Comment by dwillis** [comment]
@kevinschaul I think this would be very nice to have, yes, and I'd also like to push the GPO to add bioguide IDs separately.

**Comment by kevinschaul** [comment]
Thanks @dwillis, I'll get a PR started.
