### ISSUE TITLE
Congress Committees possible formatting issue

### ISSUE THREAD

**Issue by ShakaJohn** [unitedstates/congress-legislators#949]
Hi, 

I'm doing an import of committees for a project and my import gets thrown off at certain points. I can correct it in my import workflow, but am curious if it's supposed to be like this.

A committee name is always first, then followed by a thomas_id. Is this formatting correct? I'm seeing several places where it gets switched (SSJU, SSFR, SSEV, SSAS)

For example: SSJU

Constitution is 21 (correct)
Criminal Justice 22 (correct)
Competition Policy is 01 (correct
Immigration, Citizenship is 04 (correct)

Next it goes to wikipedia id of wikipedia: United States Senate Judiciary Subcommittee on Immigration, Refugees and Border Security then directly to id 25, which is the name below it throwing off the structure. ID 25 is supposed to come after name: Federal Courts, Oversight, Agency Action, and Federal Rights. The very last subcommittee has a name 'Privacy, Technology, and the Law' with no id following it.

  thomas_id: SSJU
  senate_committee_id: SSJU
  subcommittees:
  - name: the Constitution
    thomas_id: '21'
    wikipedia: United States Senate Judiciary Subcommittee on the Constitution, Civil
      Rights and Human Rights
  - name: Criminal Justice and Counterterrorism
    thomas_id: '22'
    wikipedia: United States Senate Judiciary Subcommittee on Crime and Terrorism
  - name: Competition Policy, Antitrust, and Consumer Rights
    thomas_id: '01'
    wikipedia: United States Senate Judiciary Subcommittee on Antitrust, Competition
      Policy and Consumer Rights
  - name: Immigration, Citizenship, and Border Safety
    thomas_id: '04'
    wikipedia: United States Senate Judiciary Subcommittee on Immigration, Refugees
      and Border Security
  - thomas_id: '25'
    name: Federal Courts, Oversight, Agency Action, and Federal Rights
  - thomas_id: '26'
    name: Intellectual Property
  - thomas_id: '27'
    name: Human Rights and the Law
  - thomas_id: '28'
    name: Privacy, Technology, and the Law
  wikipedia: United States Senate Committee on the Judiciary
  jurisdiction: The Senate Committee on the Judiciary provides oversight of the Department
    of Justice and the agencies under the Department's jurisdiction, including the
    Federal Bureau of Investigation, and the Department of Homeland Security. It also
    plays an important role in the consideration of nominations and pending legislation.
    Any legislation related to civil liberty, constitutional amendments, immigration
    and naturalization, and a variety of other topics is referred to the Committee.
  jurisdiction_source: https://www.judiciary.senate.gov/about/jurisdiction
- type: senate
  name: Senate Committee on Rules and Administration
  url: http://www.rules.senate.gov/

**Comment by JoshData** [comment]
Hello. There is no defined / required order for the fields. The files are expected to be loaded using a YAML parsing library so that the field order doesn't matter to the programmer. So if possible, I would suggest finding a YAML library in whatever language you are using.

**Comment by ShakaJohn** [comment]
Will do. Thanks for looking into it Josh, have a great day.
